package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.BHPZ;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BHPZ".
*/
public class BHPZDao extends AbstractDao<BHPZ, Long> {

    public static final String TABLENAME = "BHPZ";

    /**
     * Properties of entity BHPZ.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Bh = new Property(1, String.class, "bh", false, "BH");
        public final static Property Sbdw = new Property(2, String.class, "sbdw", false, "SBDW");
        public final static Property Dddw = new Property(3, String.class, "dddw", false, "DDDW");
        public final static Property Ycsblx = new Property(4, String.class, "ycsblx", false, "YCSBLX");
        public final static Property Czmc = new Property(5, String.class, "czmc", false, "CZMC");
        public final static Property Ycsbmc = new Property(6, String.class, "ycsbmc", false, "YCSBMC");
        public final static Property Dydj = new Property(7, long.class, "dydj", false, "DYDJ");
        public final static Property Zzcj = new Property(8, String.class, "zzcj", false, "ZZCJ");
        public final static Property Zzcj2 = new Property(9, String.class, "zzcj2", false, "ZZCJ2");
        public final static Property Bhlb = new Property(10, String.class, "bhlb", false, "BHLB");
        public final static Property Bhxh = new Property(11, String.class, "bhxh", false, "BHXH");
        public final static Property Bhxh2 = new Property(12, String.class, "bhxh2", false, "BHXH2");
        public final static Property Bhlx = new Property(13, String.class, "bhlx", false, "BHLX");
        public final static Property Bhfl = new Property(14, String.class, "bhfl", false, "BHFL");
        public final static Property Scdqjylx = new Property(15, String.class, "scdqjylx", false, "SCDQJYLX");
        public final static Property Tdlx = new Property(16, String.class, "tdlx", false, "TDLX");
        public final static Property Bz = new Property(17, String.class, "bz", false, "BZ");
        public final static Property Rjbb = new Property(18, String.class, "rjbb", false, "RJBB");
        public final static Property Tyrq = new Property(19, String.class, "tyrq", false, "TYRQ");
        public final static Property Dqjyzq = new Property(20, float.class, "dqjyzq", false, "DQJYZQ");
        public final static Property Yxdw = new Property(21, String.class, "yxdw", false, "YXDW");
        public final static Property Whdw = new Property(22, String.class, "whdw", false, "WHDW");
        public final static Property Sjdw = new Property(23, String.class, "sjdw", false, "SJDW");
        public final static Property Jjdw = new Property(24, String.class, "jjdw", false, "JJDW");
        public final static Property Xlcd = new Property(25, float.class, "xlcd", false, "XLCD");
        public final static Property Mxts = new Property(26, long.class, "mxts", false, "MXTS");
        public final static Property Sftcyx = new Property(27, String.class, "sftcyx", false, "SFTCYX");
        public final static Property Tcyxsj = new Property(28, String.class, "tcyxsj", false, "TCYXSJ");
        public final static Property Czgldw = new Property(29, String.class, "czgldw", false, "CZGLDW");
        public final static Property Czzgdydj = new Property(30, long.class, "czzgdydj", false, "CZZGDYDJ");
        public final static Property Bhmc = new Property(31, String.class, "bhmc", false, "BHMC");
        public final static Property Ccrq = new Property(32, String.class, "ccrq", false, "CCRQ");
        public final static Property Xcdqjylx = new Property(33, String.class, "xcdqjylx", false, "XCDQJYLX");
        public final static Property Bcdqjyrq = new Property(34, String.class, "bcdqjyrq", false, "BCDQJYRQ");
        public final static Property Xcdqjyrq = new Property(35, String.class, "xcdqjyrq", false, "XCDQJYRQ");
        public final static Property Vf = new Property(36, int.class, "vf", false, "VF");
        public final static Property Scdqjysj = new Property(37, String.class, "scdqjysj", false, "SCDQJYSJ");
        public final static Property Sb = new Property(38, String.class, "sb", false, "SB");
        public final static Property Ddmm = new Property(39, String.class, "ddmm", false, "DDMM");
        public final static Property Scdqjydw = new Property(40, String.class, "scdqjydw", false, "SCDQJYDW");
        public final static Property Czr = new Property(41, String.class, "czr", false, "CZR");
        public final static Property WDID = new Property(42, Long.class, "WDID", false, "WDID");
        public final static Property Cz = new Property(43, String.class, "cz", false, "CZ");
        public final static Property Bhsx = new Property(44, String.class, "bhsx", false, "BHSX");
        public final static Property Sh = new Property(45, String.class, "sh", false, "SH");
        public final static Property Shr = new Property(46, String.class, "shr", false, "SHR");
        public final static Property Shyy = new Property(47, String.class, "shyy", false, "SHYY");
        public final static Property Tb = new Property(48, String.class, "tb", false, "TB");
        public final static Property Bhmcsx = new Property(49, String.class, "bhmcsx", false, "BHMCSX");
        public final static Property Sftjyxsj = new Property(50, String.class, "sftjyxsj", false, "SFTJYXSJ");
        public final static Property Tcyxid = new Property(51, String.class, "tcyxid", false, "TCYXID");
        public final static Property Zleddy = new Property(52, long.class, "zleddy", false, "ZLEDDY");
        public final static Property Tjr = new Property(53, String.class, "tjr", false, "TJR");
        public final static Property Dwtjr = new Property(54, String.class, "dwtjr", false, "DWTJR");
        public final static Property Zcxz = new Property(55, String.class, "zcxz", false, "ZCXZ");
        public final static Property Kgbh = new Property(56, String.class, "kgbh", false, "KGBH");
        public final static Property Dycjghrq = new Property(57, String.class, "dycjghrq", false, "DYCJGHRQ");
        public final static Property Rjxd = new Property(58, String.class, "rjxd", false, "RJXD");
        public final static Property Dycjxh = new Property(59, String.class, "dycjxh", false, "DYCJXH");
        public final static Property Tyrq2 = new Property(60, String.class, "tyrq2", false, "TYRQ2");
        public final static Property Bhlbxh = new Property(61, String.class, "bhlbxh", false, "BHLBXH");
        public final static Property Tdlxxh = new Property(62, String.class, "tdlxxh", false, "TDLXXH");
        public final static Property Jgmc = new Property(63, String.class, "jgmc", false, "JGMC");
        public final static Property Jglx = new Property(64, String.class, "jglx", false, "JGLX");
        public final static Property Xcdqjysj = new Property(65, String.class, "xcdqjysj", false, "XCDQJYSJ");
        public final static Property Szpg = new Property(66, String.class, "szpg", false, "SZPG");
        public final static Property Zcdw = new Property(67, String.class, "zcdw", false, "ZCDW");
        public final static Property Jgid = new Property(68, String.class, "jgid", false, "JGID");
        public final static Property Bdzid = new Property(69, String.class, "bdzid", false, "BDZID");
        public final static Property Sjbb = new Property(70, String.class, "sjbb", false, "SJBB");
        public final static Property Edbb = new Property(71, String.class, "edbb", false, "EDBB");
        public final static Property Zqj = new Property(72, String.class, "zqj", false, "ZQJ");
        public final static Property Czsj = new Property(73, String.class, "czsj", false, "CZSJ");
        public final static Property Czpmsid = new Property(74, String.class, "czpmsid", false, "CZPMSID");
        public final static Property Jgpmsid = new Property(75, String.class, "jgpmsid", false, "JGPMSID");
        public final static Property Sb_bhpz_id = new Property(76, String.class, "sb_bhpz_id", false, "SB_BHPZ_ID");
        public final static Property Cteceddl = new Property(77, String.class, "cteceddl", false, "CTECEDDL");
        public final static Property Yxzt = new Property(78, String.class, "yxzt", false, "YXZT");
        public final static Property Zcbh = new Property(79, String.class, "zcbh", false, "ZCBH");
        public final static Property Ccbh = new Property(80, String.class, "ccbh", false, "CCBH");
        public final static Property Mntds = new Property(81, String.class, "mntds", false, "MNTDS");
        public final static Property Sztds = new Property(82, String.class, "sztds", false, "SZTDS");
        public final static Property Sbgnpz = new Property(83, String.class, "sbgnpz", false, "SBGNPZ");
        public final static Property Akzdm = new Property(84, String.class, "akzdm", false, "AKZDM");
        public final static Property Akzdlx = new Property(85, String.class, "akzdlx", false, "AKZDLX");
        public final static Property Ssakxtddmm = new Property(86, String.class, "ssakxtddmm", false, "SSAKXTDDMM");
        public final static Property Bdzlx = new Property(87, String.class, "bdzlx", false, "BDZLX");
        public final static Property Cjxx = new Property(88, String.class, "cjxx", false, "CJXX");
        public final static Property Gzlbqlx = new Property(89, String.class, "gzlbqlx", false, "GZLBQLX");
        public final static Property Sfjrzz = new Property(90, String.class, "sfjrzz", false, "SFWCXXJR");
        public final static Property Ckfs = new Property(91, String.class, "ckfs", false, "CKFS");
        public final static Property Sjcjfs = new Property(92, String.class, "sjcjfs", false, "SJCJFS");
        public final static Property Sbxs = new Property(93, String.class, "sbxs", false, "SBXS");
        public final static Property Sfltysb = new Property(94, String.class, "sfltysb", false, "SFLTYSB");
        public final static Property Ltybzbb = new Property(95, String.class, "ltybzbb", false, "LTYBZBB");
        public final static Property Sfsbm = new Property(96, String.class, "sfsbm", false, "SFSBM");
        public final static Property Sbsj = new Property(97, String.class, "sbsj", false, "SBSJ");
        public final static Property Usegddata = new Property(98, String.class, "usegddata", false, "USEGDDATA");
        public final static Property Sfbdsj = new Property(99, String.class, "sfbdsj", false, "SFBDSJ");
        public final static Property Bhsbxhxx = new Property(100, String.class, "bhsbxhxx", false, "BHSBXHXX");
        public final static Property State = new Property(101, String.class, "state", false, "STATE");
        public final static Property Sb_lx_id = new Property(102, String.class, "sb_lx_id", false, "SB_LS_ID");
        public final static Property Czsx = new Property(103, String.class, "czsx", false, "CZSX");
        public final static Property CaseValidate = new Property(104, String.class, "caseValidate", false, "CASEVALIDATE");
        public final static Property Hzsj = new Property(105, String.class, "hzsj", false, "HZSJ");
        public final static Property Ls_validateformat = new Property(106, String.class, "ls_validateformat", false, "LS_VALIDATEFORMAT");
        public final static Property Sbczlx = new Property(107, String.class, "sbczlx", false, "SBCZLX");
        public final static Property Sfxtlr = new Property(108, String.class, "sfxtlr", false, "SFXTLR");
        public final static Property Shxtlr = new Property(109, String.class, "shxtlr", false, "SHXTLR");
        public final static Property Validateformat = new Property(110, String.class, "validateformat", false, "VALIDATEFORMAT");
        public final static Property Wj_dw = new Property(111, String.class, "wj_dw", false, "WJ_DW");
        public final static Property Wj_ls_id = new Property(112, String.class, "wj_ls_id", false, "WJ_LS_ID");
        public final static Property Xp = new Property(113, String.class, "xp", false, "XP");
        public final static Property Jzxh = new Property(114, String.class, "jzxh", false, "JZXH");
        public final static Property Bksl = new Property(115, int.class, "bksl", false, "BKSL");
        public final static Property Icdwjmc = new Property(116, String.class, "icdwjmc", false, "ICDWJMC");
        public final static Property Czgldw_gd = new Property(117, String.class, "czgldw_gd", false, "CZGLDW_GD");
        public final static Property Dddw_gd = new Property(118, String.class, "dddw_gd", false, "DDDW_GD");
        public final static Property Sbdw_gd = new Property(119, String.class, "sbdw_gd", false, "SBDW_GD");
        public final static Property Shsj = new Property(120, String.class, "shsj", false, "SHSJ");
        public final static Property Sfsch = new Property(121, String.class, "sfsch", false, "SFSCH");
        public final static Property Ed_tag = new Property(122, String.class, "ed_tag", false, "ED_TAG");
        public final static Property Ljqsl = new Property(123, String.class, "ljqsl", false, "LJQSL");
        public final static Property Ljqzzcj = new Property(124, String.class, "ljqzzcj", false, "LJQZZCJ");
        public final static Property Ljqxh = new Property(125, String.class, "ljqxh", false, "LJQXH");
        public final static Property Sfjdhzz = new Property(126, String.class, "sfjdhzz", false, "SFJDHZZ");
        public final static Property Sw_id = new Property(127, String.class, "sw_id", false, "SWID");
        public final static Property Jy = new Property(128, String.class, "jy", false, "JY");
    }


    public BHPZDao(DaoConfig config) {
        super(config);
    }
    
    public BHPZDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BHPZ entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bh = entity.getBh();
        if (bh != null) {
            stmt.bindString(2, bh);
        }
 
        String sbdw = entity.getSbdw();
        if (sbdw != null) {
            stmt.bindString(3, sbdw);
        }
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(4, dddw);
        }
 
        String ycsblx = entity.getYcsblx();
        if (ycsblx != null) {
            stmt.bindString(5, ycsblx);
        }
 
        String czmc = entity.getCzmc();
        if (czmc != null) {
            stmt.bindString(6, czmc);
        }
 
        String ycsbmc = entity.getYcsbmc();
        if (ycsbmc != null) {
            stmt.bindString(7, ycsbmc);
        }
        stmt.bindLong(8, entity.getDydj());
 
        String zzcj = entity.getZzcj();
        if (zzcj != null) {
            stmt.bindString(9, zzcj);
        }
 
        String zzcj2 = entity.getZzcj2();
        if (zzcj2 != null) {
            stmt.bindString(10, zzcj2);
        }
 
        String bhlb = entity.getBhlb();
        if (bhlb != null) {
            stmt.bindString(11, bhlb);
        }
 
        String bhxh = entity.getBhxh();
        if (bhxh != null) {
            stmt.bindString(12, bhxh);
        }
 
        String bhxh2 = entity.getBhxh2();
        if (bhxh2 != null) {
            stmt.bindString(13, bhxh2);
        }
 
        String bhlx = entity.getBhlx();
        if (bhlx != null) {
            stmt.bindString(14, bhlx);
        }
 
        String bhfl = entity.getBhfl();
        if (bhfl != null) {
            stmt.bindString(15, bhfl);
        }
 
        String scdqjylx = entity.getScdqjylx();
        if (scdqjylx != null) {
            stmt.bindString(16, scdqjylx);
        }
 
        String tdlx = entity.getTdlx();
        if (tdlx != null) {
            stmt.bindString(17, tdlx);
        }
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(18, bz);
        }
 
        String rjbb = entity.getRjbb();
        if (rjbb != null) {
            stmt.bindString(19, rjbb);
        }
 
        String tyrq = entity.getTyrq();
        if (tyrq != null) {
            stmt.bindString(20, tyrq);
        }
        stmt.bindDouble(21, entity.getDqjyzq());
 
        String yxdw = entity.getYxdw();
        if (yxdw != null) {
            stmt.bindString(22, yxdw);
        }
 
        String whdw = entity.getWhdw();
        if (whdw != null) {
            stmt.bindString(23, whdw);
        }
 
        String sjdw = entity.getSjdw();
        if (sjdw != null) {
            stmt.bindString(24, sjdw);
        }
 
        String jjdw = entity.getJjdw();
        if (jjdw != null) {
            stmt.bindString(25, jjdw);
        }
        stmt.bindDouble(26, entity.getXlcd());
        stmt.bindLong(27, entity.getMxts());
 
        String sftcyx = entity.getSftcyx();
        if (sftcyx != null) {
            stmt.bindString(28, sftcyx);
        }
 
        String tcyxsj = entity.getTcyxsj();
        if (tcyxsj != null) {
            stmt.bindString(29, tcyxsj);
        }
 
        String czgldw = entity.getCzgldw();
        if (czgldw != null) {
            stmt.bindString(30, czgldw);
        }
        stmt.bindLong(31, entity.getCzzgdydj());
 
        String bhmc = entity.getBhmc();
        if (bhmc != null) {
            stmt.bindString(32, bhmc);
        }
 
        String ccrq = entity.getCcrq();
        if (ccrq != null) {
            stmt.bindString(33, ccrq);
        }
 
        String xcdqjylx = entity.getXcdqjylx();
        if (xcdqjylx != null) {
            stmt.bindString(34, xcdqjylx);
        }
 
        String bcdqjyrq = entity.getBcdqjyrq();
        if (bcdqjyrq != null) {
            stmt.bindString(35, bcdqjyrq);
        }
 
        String xcdqjyrq = entity.getXcdqjyrq();
        if (xcdqjyrq != null) {
            stmt.bindString(36, xcdqjyrq);
        }
        stmt.bindLong(37, entity.getVf());
 
        String scdqjysj = entity.getScdqjysj();
        if (scdqjysj != null) {
            stmt.bindString(38, scdqjysj);
        }
 
        String sb = entity.getSb();
        if (sb != null) {
            stmt.bindString(39, sb);
        }
 
        String ddmm = entity.getDdmm();
        if (ddmm != null) {
            stmt.bindString(40, ddmm);
        }
 
        String scdqjydw = entity.getScdqjydw();
        if (scdqjydw != null) {
            stmt.bindString(41, scdqjydw);
        }
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(42, czr);
        }
 
        Long WDID = entity.getWDID();
        if (WDID != null) {
            stmt.bindLong(43, WDID);
        }
 
        String cz = entity.getCz();
        if (cz != null) {
            stmt.bindString(44, cz);
        }
 
        String bhsx = entity.getBhsx();
        if (bhsx != null) {
            stmt.bindString(45, bhsx);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(46, sh);
        }
 
        String shr = entity.getShr();
        if (shr != null) {
            stmt.bindString(47, shr);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(48, shyy);
        }
 
        String tb = entity.getTb();
        if (tb != null) {
            stmt.bindString(49, tb);
        }
 
        String bhmcsx = entity.getBhmcsx();
        if (bhmcsx != null) {
            stmt.bindString(50, bhmcsx);
        }
 
        String sftjyxsj = entity.getSftjyxsj();
        if (sftjyxsj != null) {
            stmt.bindString(51, sftjyxsj);
        }
 
        String tcyxid = entity.getTcyxid();
        if (tcyxid != null) {
            stmt.bindString(52, tcyxid);
        }
        stmt.bindLong(53, entity.getZleddy());
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(54, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(55, dwtjr);
        }
 
        String zcxz = entity.getZcxz();
        if (zcxz != null) {
            stmt.bindString(56, zcxz);
        }
 
        String kgbh = entity.getKgbh();
        if (kgbh != null) {
            stmt.bindString(57, kgbh);
        }
 
        String dycjghrq = entity.getDycjghrq();
        if (dycjghrq != null) {
            stmt.bindString(58, dycjghrq);
        }
 
        String rjxd = entity.getRjxd();
        if (rjxd != null) {
            stmt.bindString(59, rjxd);
        }
 
        String dycjxh = entity.getDycjxh();
        if (dycjxh != null) {
            stmt.bindString(60, dycjxh);
        }
 
        String tyrq2 = entity.getTyrq2();
        if (tyrq2 != null) {
            stmt.bindString(61, tyrq2);
        }
 
        String bhlbxh = entity.getBhlbxh();
        if (bhlbxh != null) {
            stmt.bindString(62, bhlbxh);
        }
 
        String tdlxxh = entity.getTdlxxh();
        if (tdlxxh != null) {
            stmt.bindString(63, tdlxxh);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(64, jgmc);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(65, jglx);
        }
 
        String xcdqjysj = entity.getXcdqjysj();
        if (xcdqjysj != null) {
            stmt.bindString(66, xcdqjysj);
        }
 
        String szpg = entity.getSzpg();
        if (szpg != null) {
            stmt.bindString(67, szpg);
        }
 
        String zcdw = entity.getZcdw();
        if (zcdw != null) {
            stmt.bindString(68, zcdw);
        }
 
        String jgid = entity.getJgid();
        if (jgid != null) {
            stmt.bindString(69, jgid);
        }
 
        String bdzid = entity.getBdzid();
        if (bdzid != null) {
            stmt.bindString(70, bdzid);
        }
 
        String sjbb = entity.getSjbb();
        if (sjbb != null) {
            stmt.bindString(71, sjbb);
        }
 
        String edbb = entity.getEdbb();
        if (edbb != null) {
            stmt.bindString(72, edbb);
        }
 
        String zqj = entity.getZqj();
        if (zqj != null) {
            stmt.bindString(73, zqj);
        }
 
        String czsj = entity.getCzsj();
        if (czsj != null) {
            stmt.bindString(74, czsj);
        }
 
        String czpmsid = entity.getCzpmsid();
        if (czpmsid != null) {
            stmt.bindString(75, czpmsid);
        }
 
        String jgpmsid = entity.getJgpmsid();
        if (jgpmsid != null) {
            stmt.bindString(76, jgpmsid);
        }
 
        String sb_bhpz_id = entity.getSb_bhpz_id();
        if (sb_bhpz_id != null) {
            stmt.bindString(77, sb_bhpz_id);
        }
 
        String cteceddl = entity.getCteceddl();
        if (cteceddl != null) {
            stmt.bindString(78, cteceddl);
        }
 
        String yxzt = entity.getYxzt();
        if (yxzt != null) {
            stmt.bindString(79, yxzt);
        }
 
        String zcbh = entity.getZcbh();
        if (zcbh != null) {
            stmt.bindString(80, zcbh);
        }
 
        String ccbh = entity.getCcbh();
        if (ccbh != null) {
            stmt.bindString(81, ccbh);
        }
 
        String mntds = entity.getMntds();
        if (mntds != null) {
            stmt.bindString(82, mntds);
        }
 
        String sztds = entity.getSztds();
        if (sztds != null) {
            stmt.bindString(83, sztds);
        }
 
        String sbgnpz = entity.getSbgnpz();
        if (sbgnpz != null) {
            stmt.bindString(84, sbgnpz);
        }
 
        String akzdm = entity.getAkzdm();
        if (akzdm != null) {
            stmt.bindString(85, akzdm);
        }
 
        String akzdlx = entity.getAkzdlx();
        if (akzdlx != null) {
            stmt.bindString(86, akzdlx);
        }
 
        String ssakxtddmm = entity.getSsakxtddmm();
        if (ssakxtddmm != null) {
            stmt.bindString(87, ssakxtddmm);
        }
 
        String bdzlx = entity.getBdzlx();
        if (bdzlx != null) {
            stmt.bindString(88, bdzlx);
        }
 
        String cjxx = entity.getCjxx();
        if (cjxx != null) {
            stmt.bindString(89, cjxx);
        }
 
        String gzlbqlx = entity.getGzlbqlx();
        if (gzlbqlx != null) {
            stmt.bindString(90, gzlbqlx);
        }
 
        String sfjrzz = entity.getSfjrzz();
        if (sfjrzz != null) {
            stmt.bindString(91, sfjrzz);
        }
 
        String ckfs = entity.getCkfs();
        if (ckfs != null) {
            stmt.bindString(92, ckfs);
        }
 
        String sjcjfs = entity.getSjcjfs();
        if (sjcjfs != null) {
            stmt.bindString(93, sjcjfs);
        }
 
        String sbxs = entity.getSbxs();
        if (sbxs != null) {
            stmt.bindString(94, sbxs);
        }
 
        String sfltysb = entity.getSfltysb();
        if (sfltysb != null) {
            stmt.bindString(95, sfltysb);
        }
 
        String ltybzbb = entity.getLtybzbb();
        if (ltybzbb != null) {
            stmt.bindString(96, ltybzbb);
        }
 
        String sfsbm = entity.getSfsbm();
        if (sfsbm != null) {
            stmt.bindString(97, sfsbm);
        }
 
        String sbsj = entity.getSbsj();
        if (sbsj != null) {
            stmt.bindString(98, sbsj);
        }
 
        String usegddata = entity.getUsegddata();
        if (usegddata != null) {
            stmt.bindString(99, usegddata);
        }
 
        String sfbdsj = entity.getSfbdsj();
        if (sfbdsj != null) {
            stmt.bindString(100, sfbdsj);
        }
 
        String bhsbxhxx = entity.getBhsbxhxx();
        if (bhsbxhxx != null) {
            stmt.bindString(101, bhsbxhxx);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(102, state);
        }
 
        String sb_lx_id = entity.getSb_lx_id();
        if (sb_lx_id != null) {
            stmt.bindString(103, sb_lx_id);
        }
 
        String czsx = entity.getCzsx();
        if (czsx != null) {
            stmt.bindString(104, czsx);
        }
 
        String caseValidate = entity.getCaseValidate();
        if (caseValidate != null) {
            stmt.bindString(105, caseValidate);
        }
 
        String hzsj = entity.getHzsj();
        if (hzsj != null) {
            stmt.bindString(106, hzsj);
        }
 
        String ls_validateformat = entity.getLs_validateformat();
        if (ls_validateformat != null) {
            stmt.bindString(107, ls_validateformat);
        }
 
        String sbczlx = entity.getSbczlx();
        if (sbczlx != null) {
            stmt.bindString(108, sbczlx);
        }
 
        String sfxtlr = entity.getSfxtlr();
        if (sfxtlr != null) {
            stmt.bindString(109, sfxtlr);
        }
 
        String shxtlr = entity.getShxtlr();
        if (shxtlr != null) {
            stmt.bindString(110, shxtlr);
        }
 
        String validateformat = entity.getValidateformat();
        if (validateformat != null) {
            stmt.bindString(111, validateformat);
        }
 
        String wj_dw = entity.getWj_dw();
        if (wj_dw != null) {
            stmt.bindString(112, wj_dw);
        }
 
        String wj_ls_id = entity.getWj_ls_id();
        if (wj_ls_id != null) {
            stmt.bindString(113, wj_ls_id);
        }
 
        String xp = entity.getXp();
        if (xp != null) {
            stmt.bindString(114, xp);
        }
 
        String jzxh = entity.getJzxh();
        if (jzxh != null) {
            stmt.bindString(115, jzxh);
        }
        stmt.bindLong(116, entity.getBksl());
 
        String icdwjmc = entity.getIcdwjmc();
        if (icdwjmc != null) {
            stmt.bindString(117, icdwjmc);
        }
 
        String czgldw_gd = entity.getCzgldw_gd();
        if (czgldw_gd != null) {
            stmt.bindString(118, czgldw_gd);
        }
 
        String dddw_gd = entity.getDddw_gd();
        if (dddw_gd != null) {
            stmt.bindString(119, dddw_gd);
        }
 
        String sbdw_gd = entity.getSbdw_gd();
        if (sbdw_gd != null) {
            stmt.bindString(120, sbdw_gd);
        }
 
        String shsj = entity.getShsj();
        if (shsj != null) {
            stmt.bindString(121, shsj);
        }
 
        String sfsch = entity.getSfsch();
        if (sfsch != null) {
            stmt.bindString(122, sfsch);
        }
 
        String ed_tag = entity.getEd_tag();
        if (ed_tag != null) {
            stmt.bindString(123, ed_tag);
        }
 
        String ljqsl = entity.getLjqsl();
        if (ljqsl != null) {
            stmt.bindString(124, ljqsl);
        }
 
        String ljqzzcj = entity.getLjqzzcj();
        if (ljqzzcj != null) {
            stmt.bindString(125, ljqzzcj);
        }
 
        String ljqxh = entity.getLjqxh();
        if (ljqxh != null) {
            stmt.bindString(126, ljqxh);
        }
 
        String sfjdhzz = entity.getSfjdhzz();
        if (sfjdhzz != null) {
            stmt.bindString(127, sfjdhzz);
        }
 
        String sw_id = entity.getSw_id();
        if (sw_id != null) {
            stmt.bindString(128, sw_id);
        }
 
        String jy = entity.getJy();
        if (jy != null) {
            stmt.bindString(129, jy);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BHPZ entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bh = entity.getBh();
        if (bh != null) {
            stmt.bindString(2, bh);
        }
 
        String sbdw = entity.getSbdw();
        if (sbdw != null) {
            stmt.bindString(3, sbdw);
        }
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(4, dddw);
        }
 
        String ycsblx = entity.getYcsblx();
        if (ycsblx != null) {
            stmt.bindString(5, ycsblx);
        }
 
        String czmc = entity.getCzmc();
        if (czmc != null) {
            stmt.bindString(6, czmc);
        }
 
        String ycsbmc = entity.getYcsbmc();
        if (ycsbmc != null) {
            stmt.bindString(7, ycsbmc);
        }
        stmt.bindLong(8, entity.getDydj());
 
        String zzcj = entity.getZzcj();
        if (zzcj != null) {
            stmt.bindString(9, zzcj);
        }
 
        String zzcj2 = entity.getZzcj2();
        if (zzcj2 != null) {
            stmt.bindString(10, zzcj2);
        }
 
        String bhlb = entity.getBhlb();
        if (bhlb != null) {
            stmt.bindString(11, bhlb);
        }
 
        String bhxh = entity.getBhxh();
        if (bhxh != null) {
            stmt.bindString(12, bhxh);
        }
 
        String bhxh2 = entity.getBhxh2();
        if (bhxh2 != null) {
            stmt.bindString(13, bhxh2);
        }
 
        String bhlx = entity.getBhlx();
        if (bhlx != null) {
            stmt.bindString(14, bhlx);
        }
 
        String bhfl = entity.getBhfl();
        if (bhfl != null) {
            stmt.bindString(15, bhfl);
        }
 
        String scdqjylx = entity.getScdqjylx();
        if (scdqjylx != null) {
            stmt.bindString(16, scdqjylx);
        }
 
        String tdlx = entity.getTdlx();
        if (tdlx != null) {
            stmt.bindString(17, tdlx);
        }
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(18, bz);
        }
 
        String rjbb = entity.getRjbb();
        if (rjbb != null) {
            stmt.bindString(19, rjbb);
        }
 
        String tyrq = entity.getTyrq();
        if (tyrq != null) {
            stmt.bindString(20, tyrq);
        }
        stmt.bindDouble(21, entity.getDqjyzq());
 
        String yxdw = entity.getYxdw();
        if (yxdw != null) {
            stmt.bindString(22, yxdw);
        }
 
        String whdw = entity.getWhdw();
        if (whdw != null) {
            stmt.bindString(23, whdw);
        }
 
        String sjdw = entity.getSjdw();
        if (sjdw != null) {
            stmt.bindString(24, sjdw);
        }
 
        String jjdw = entity.getJjdw();
        if (jjdw != null) {
            stmt.bindString(25, jjdw);
        }
        stmt.bindDouble(26, entity.getXlcd());
        stmt.bindLong(27, entity.getMxts());
 
        String sftcyx = entity.getSftcyx();
        if (sftcyx != null) {
            stmt.bindString(28, sftcyx);
        }
 
        String tcyxsj = entity.getTcyxsj();
        if (tcyxsj != null) {
            stmt.bindString(29, tcyxsj);
        }
 
        String czgldw = entity.getCzgldw();
        if (czgldw != null) {
            stmt.bindString(30, czgldw);
        }
        stmt.bindLong(31, entity.getCzzgdydj());
 
        String bhmc = entity.getBhmc();
        if (bhmc != null) {
            stmt.bindString(32, bhmc);
        }
 
        String ccrq = entity.getCcrq();
        if (ccrq != null) {
            stmt.bindString(33, ccrq);
        }
 
        String xcdqjylx = entity.getXcdqjylx();
        if (xcdqjylx != null) {
            stmt.bindString(34, xcdqjylx);
        }
 
        String bcdqjyrq = entity.getBcdqjyrq();
        if (bcdqjyrq != null) {
            stmt.bindString(35, bcdqjyrq);
        }
 
        String xcdqjyrq = entity.getXcdqjyrq();
        if (xcdqjyrq != null) {
            stmt.bindString(36, xcdqjyrq);
        }
        stmt.bindLong(37, entity.getVf());
 
        String scdqjysj = entity.getScdqjysj();
        if (scdqjysj != null) {
            stmt.bindString(38, scdqjysj);
        }
 
        String sb = entity.getSb();
        if (sb != null) {
            stmt.bindString(39, sb);
        }
 
        String ddmm = entity.getDdmm();
        if (ddmm != null) {
            stmt.bindString(40, ddmm);
        }
 
        String scdqjydw = entity.getScdqjydw();
        if (scdqjydw != null) {
            stmt.bindString(41, scdqjydw);
        }
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(42, czr);
        }
 
        Long WDID = entity.getWDID();
        if (WDID != null) {
            stmt.bindLong(43, WDID);
        }
 
        String cz = entity.getCz();
        if (cz != null) {
            stmt.bindString(44, cz);
        }
 
        String bhsx = entity.getBhsx();
        if (bhsx != null) {
            stmt.bindString(45, bhsx);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(46, sh);
        }
 
        String shr = entity.getShr();
        if (shr != null) {
            stmt.bindString(47, shr);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(48, shyy);
        }
 
        String tb = entity.getTb();
        if (tb != null) {
            stmt.bindString(49, tb);
        }
 
        String bhmcsx = entity.getBhmcsx();
        if (bhmcsx != null) {
            stmt.bindString(50, bhmcsx);
        }
 
        String sftjyxsj = entity.getSftjyxsj();
        if (sftjyxsj != null) {
            stmt.bindString(51, sftjyxsj);
        }
 
        String tcyxid = entity.getTcyxid();
        if (tcyxid != null) {
            stmt.bindString(52, tcyxid);
        }
        stmt.bindLong(53, entity.getZleddy());
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(54, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(55, dwtjr);
        }
 
        String zcxz = entity.getZcxz();
        if (zcxz != null) {
            stmt.bindString(56, zcxz);
        }
 
        String kgbh = entity.getKgbh();
        if (kgbh != null) {
            stmt.bindString(57, kgbh);
        }
 
        String dycjghrq = entity.getDycjghrq();
        if (dycjghrq != null) {
            stmt.bindString(58, dycjghrq);
        }
 
        String rjxd = entity.getRjxd();
        if (rjxd != null) {
            stmt.bindString(59, rjxd);
        }
 
        String dycjxh = entity.getDycjxh();
        if (dycjxh != null) {
            stmt.bindString(60, dycjxh);
        }
 
        String tyrq2 = entity.getTyrq2();
        if (tyrq2 != null) {
            stmt.bindString(61, tyrq2);
        }
 
        String bhlbxh = entity.getBhlbxh();
        if (bhlbxh != null) {
            stmt.bindString(62, bhlbxh);
        }
 
        String tdlxxh = entity.getTdlxxh();
        if (tdlxxh != null) {
            stmt.bindString(63, tdlxxh);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(64, jgmc);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(65, jglx);
        }
 
        String xcdqjysj = entity.getXcdqjysj();
        if (xcdqjysj != null) {
            stmt.bindString(66, xcdqjysj);
        }
 
        String szpg = entity.getSzpg();
        if (szpg != null) {
            stmt.bindString(67, szpg);
        }
 
        String zcdw = entity.getZcdw();
        if (zcdw != null) {
            stmt.bindString(68, zcdw);
        }
 
        String jgid = entity.getJgid();
        if (jgid != null) {
            stmt.bindString(69, jgid);
        }
 
        String bdzid = entity.getBdzid();
        if (bdzid != null) {
            stmt.bindString(70, bdzid);
        }
 
        String sjbb = entity.getSjbb();
        if (sjbb != null) {
            stmt.bindString(71, sjbb);
        }
 
        String edbb = entity.getEdbb();
        if (edbb != null) {
            stmt.bindString(72, edbb);
        }
 
        String zqj = entity.getZqj();
        if (zqj != null) {
            stmt.bindString(73, zqj);
        }
 
        String czsj = entity.getCzsj();
        if (czsj != null) {
            stmt.bindString(74, czsj);
        }
 
        String czpmsid = entity.getCzpmsid();
        if (czpmsid != null) {
            stmt.bindString(75, czpmsid);
        }
 
        String jgpmsid = entity.getJgpmsid();
        if (jgpmsid != null) {
            stmt.bindString(76, jgpmsid);
        }
 
        String sb_bhpz_id = entity.getSb_bhpz_id();
        if (sb_bhpz_id != null) {
            stmt.bindString(77, sb_bhpz_id);
        }
 
        String cteceddl = entity.getCteceddl();
        if (cteceddl != null) {
            stmt.bindString(78, cteceddl);
        }
 
        String yxzt = entity.getYxzt();
        if (yxzt != null) {
            stmt.bindString(79, yxzt);
        }
 
        String zcbh = entity.getZcbh();
        if (zcbh != null) {
            stmt.bindString(80, zcbh);
        }
 
        String ccbh = entity.getCcbh();
        if (ccbh != null) {
            stmt.bindString(81, ccbh);
        }
 
        String mntds = entity.getMntds();
        if (mntds != null) {
            stmt.bindString(82, mntds);
        }
 
        String sztds = entity.getSztds();
        if (sztds != null) {
            stmt.bindString(83, sztds);
        }
 
        String sbgnpz = entity.getSbgnpz();
        if (sbgnpz != null) {
            stmt.bindString(84, sbgnpz);
        }
 
        String akzdm = entity.getAkzdm();
        if (akzdm != null) {
            stmt.bindString(85, akzdm);
        }
 
        String akzdlx = entity.getAkzdlx();
        if (akzdlx != null) {
            stmt.bindString(86, akzdlx);
        }
 
        String ssakxtddmm = entity.getSsakxtddmm();
        if (ssakxtddmm != null) {
            stmt.bindString(87, ssakxtddmm);
        }
 
        String bdzlx = entity.getBdzlx();
        if (bdzlx != null) {
            stmt.bindString(88, bdzlx);
        }
 
        String cjxx = entity.getCjxx();
        if (cjxx != null) {
            stmt.bindString(89, cjxx);
        }
 
        String gzlbqlx = entity.getGzlbqlx();
        if (gzlbqlx != null) {
            stmt.bindString(90, gzlbqlx);
        }
 
        String sfjrzz = entity.getSfjrzz();
        if (sfjrzz != null) {
            stmt.bindString(91, sfjrzz);
        }
 
        String ckfs = entity.getCkfs();
        if (ckfs != null) {
            stmt.bindString(92, ckfs);
        }
 
        String sjcjfs = entity.getSjcjfs();
        if (sjcjfs != null) {
            stmt.bindString(93, sjcjfs);
        }
 
        String sbxs = entity.getSbxs();
        if (sbxs != null) {
            stmt.bindString(94, sbxs);
        }
 
        String sfltysb = entity.getSfltysb();
        if (sfltysb != null) {
            stmt.bindString(95, sfltysb);
        }
 
        String ltybzbb = entity.getLtybzbb();
        if (ltybzbb != null) {
            stmt.bindString(96, ltybzbb);
        }
 
        String sfsbm = entity.getSfsbm();
        if (sfsbm != null) {
            stmt.bindString(97, sfsbm);
        }
 
        String sbsj = entity.getSbsj();
        if (sbsj != null) {
            stmt.bindString(98, sbsj);
        }
 
        String usegddata = entity.getUsegddata();
        if (usegddata != null) {
            stmt.bindString(99, usegddata);
        }
 
        String sfbdsj = entity.getSfbdsj();
        if (sfbdsj != null) {
            stmt.bindString(100, sfbdsj);
        }
 
        String bhsbxhxx = entity.getBhsbxhxx();
        if (bhsbxhxx != null) {
            stmt.bindString(101, bhsbxhxx);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(102, state);
        }
 
        String sb_lx_id = entity.getSb_lx_id();
        if (sb_lx_id != null) {
            stmt.bindString(103, sb_lx_id);
        }
 
        String czsx = entity.getCzsx();
        if (czsx != null) {
            stmt.bindString(104, czsx);
        }
 
        String caseValidate = entity.getCaseValidate();
        if (caseValidate != null) {
            stmt.bindString(105, caseValidate);
        }
 
        String hzsj = entity.getHzsj();
        if (hzsj != null) {
            stmt.bindString(106, hzsj);
        }
 
        String ls_validateformat = entity.getLs_validateformat();
        if (ls_validateformat != null) {
            stmt.bindString(107, ls_validateformat);
        }
 
        String sbczlx = entity.getSbczlx();
        if (sbczlx != null) {
            stmt.bindString(108, sbczlx);
        }
 
        String sfxtlr = entity.getSfxtlr();
        if (sfxtlr != null) {
            stmt.bindString(109, sfxtlr);
        }
 
        String shxtlr = entity.getShxtlr();
        if (shxtlr != null) {
            stmt.bindString(110, shxtlr);
        }
 
        String validateformat = entity.getValidateformat();
        if (validateformat != null) {
            stmt.bindString(111, validateformat);
        }
 
        String wj_dw = entity.getWj_dw();
        if (wj_dw != null) {
            stmt.bindString(112, wj_dw);
        }
 
        String wj_ls_id = entity.getWj_ls_id();
        if (wj_ls_id != null) {
            stmt.bindString(113, wj_ls_id);
        }
 
        String xp = entity.getXp();
        if (xp != null) {
            stmt.bindString(114, xp);
        }
 
        String jzxh = entity.getJzxh();
        if (jzxh != null) {
            stmt.bindString(115, jzxh);
        }
        stmt.bindLong(116, entity.getBksl());
 
        String icdwjmc = entity.getIcdwjmc();
        if (icdwjmc != null) {
            stmt.bindString(117, icdwjmc);
        }
 
        String czgldw_gd = entity.getCzgldw_gd();
        if (czgldw_gd != null) {
            stmt.bindString(118, czgldw_gd);
        }
 
        String dddw_gd = entity.getDddw_gd();
        if (dddw_gd != null) {
            stmt.bindString(119, dddw_gd);
        }
 
        String sbdw_gd = entity.getSbdw_gd();
        if (sbdw_gd != null) {
            stmt.bindString(120, sbdw_gd);
        }
 
        String shsj = entity.getShsj();
        if (shsj != null) {
            stmt.bindString(121, shsj);
        }
 
        String sfsch = entity.getSfsch();
        if (sfsch != null) {
            stmt.bindString(122, sfsch);
        }
 
        String ed_tag = entity.getEd_tag();
        if (ed_tag != null) {
            stmt.bindString(123, ed_tag);
        }
 
        String ljqsl = entity.getLjqsl();
        if (ljqsl != null) {
            stmt.bindString(124, ljqsl);
        }
 
        String ljqzzcj = entity.getLjqzzcj();
        if (ljqzzcj != null) {
            stmt.bindString(125, ljqzzcj);
        }
 
        String ljqxh = entity.getLjqxh();
        if (ljqxh != null) {
            stmt.bindString(126, ljqxh);
        }
 
        String sfjdhzz = entity.getSfjdhzz();
        if (sfjdhzz != null) {
            stmt.bindString(127, sfjdhzz);
        }
 
        String sw_id = entity.getSw_id();
        if (sw_id != null) {
            stmt.bindString(128, sw_id);
        }
 
        String jy = entity.getJy();
        if (jy != null) {
            stmt.bindString(129, jy);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BHPZ readEntity(Cursor cursor, int offset) {
        BHPZ entity = new BHPZ( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bh
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sbdw
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dddw
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ycsblx
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // czmc
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ycsbmc
            cursor.getLong(offset + 7), // dydj
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // zzcj
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // zzcj2
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // bhlb
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // bhxh
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // bhxh2
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // bhlx
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // bhfl
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // scdqjylx
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tdlx
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // bz
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // rjbb
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // tyrq
            cursor.getFloat(offset + 20), // dqjyzq
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // yxdw
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // whdw
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // sjdw
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // jjdw
            cursor.getFloat(offset + 25), // xlcd
            cursor.getLong(offset + 26), // mxts
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // sftcyx
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // tcyxsj
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // czgldw
            cursor.getLong(offset + 30), // czzgdydj
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // bhmc
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // ccrq
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // xcdqjylx
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // bcdqjyrq
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // xcdqjyrq
            cursor.getInt(offset + 36), // vf
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // scdqjysj
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // sb
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // ddmm
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // scdqjydw
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // czr
            cursor.isNull(offset + 42) ? null : cursor.getLong(offset + 42), // WDID
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // cz
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // bhsx
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // sh
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // shr
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // shyy
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // tb
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // bhmcsx
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // sftjyxsj
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // tcyxid
            cursor.getLong(offset + 52), // zleddy
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // tjr
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // dwtjr
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // zcxz
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // kgbh
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // dycjghrq
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // rjxd
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // dycjxh
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // tyrq2
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // bhlbxh
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // tdlxxh
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // jgmc
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // jglx
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // xcdqjysj
            cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66), // szpg
            cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67), // zcdw
            cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68), // jgid
            cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69), // bdzid
            cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70), // sjbb
            cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71), // edbb
            cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72), // zqj
            cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73), // czsj
            cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74), // czpmsid
            cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75), // jgpmsid
            cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76), // sb_bhpz_id
            cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77), // cteceddl
            cursor.isNull(offset + 78) ? null : cursor.getString(offset + 78), // yxzt
            cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79), // zcbh
            cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80), // ccbh
            cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81), // mntds
            cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82), // sztds
            cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83), // sbgnpz
            cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84), // akzdm
            cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85), // akzdlx
            cursor.isNull(offset + 86) ? null : cursor.getString(offset + 86), // ssakxtddmm
            cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87), // bdzlx
            cursor.isNull(offset + 88) ? null : cursor.getString(offset + 88), // cjxx
            cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89), // gzlbqlx
            cursor.isNull(offset + 90) ? null : cursor.getString(offset + 90), // sfjrzz
            cursor.isNull(offset + 91) ? null : cursor.getString(offset + 91), // ckfs
            cursor.isNull(offset + 92) ? null : cursor.getString(offset + 92), // sjcjfs
            cursor.isNull(offset + 93) ? null : cursor.getString(offset + 93), // sbxs
            cursor.isNull(offset + 94) ? null : cursor.getString(offset + 94), // sfltysb
            cursor.isNull(offset + 95) ? null : cursor.getString(offset + 95), // ltybzbb
            cursor.isNull(offset + 96) ? null : cursor.getString(offset + 96), // sfsbm
            cursor.isNull(offset + 97) ? null : cursor.getString(offset + 97), // sbsj
            cursor.isNull(offset + 98) ? null : cursor.getString(offset + 98), // usegddata
            cursor.isNull(offset + 99) ? null : cursor.getString(offset + 99), // sfbdsj
            cursor.isNull(offset + 100) ? null : cursor.getString(offset + 100), // bhsbxhxx
            cursor.isNull(offset + 101) ? null : cursor.getString(offset + 101), // state
            cursor.isNull(offset + 102) ? null : cursor.getString(offset + 102), // sb_lx_id
            cursor.isNull(offset + 103) ? null : cursor.getString(offset + 103), // czsx
            cursor.isNull(offset + 104) ? null : cursor.getString(offset + 104), // caseValidate
            cursor.isNull(offset + 105) ? null : cursor.getString(offset + 105), // hzsj
            cursor.isNull(offset + 106) ? null : cursor.getString(offset + 106), // ls_validateformat
            cursor.isNull(offset + 107) ? null : cursor.getString(offset + 107), // sbczlx
            cursor.isNull(offset + 108) ? null : cursor.getString(offset + 108), // sfxtlr
            cursor.isNull(offset + 109) ? null : cursor.getString(offset + 109), // shxtlr
            cursor.isNull(offset + 110) ? null : cursor.getString(offset + 110), // validateformat
            cursor.isNull(offset + 111) ? null : cursor.getString(offset + 111), // wj_dw
            cursor.isNull(offset + 112) ? null : cursor.getString(offset + 112), // wj_ls_id
            cursor.isNull(offset + 113) ? null : cursor.getString(offset + 113), // xp
            cursor.isNull(offset + 114) ? null : cursor.getString(offset + 114), // jzxh
            cursor.getInt(offset + 115), // bksl
            cursor.isNull(offset + 116) ? null : cursor.getString(offset + 116), // icdwjmc
            cursor.isNull(offset + 117) ? null : cursor.getString(offset + 117), // czgldw_gd
            cursor.isNull(offset + 118) ? null : cursor.getString(offset + 118), // dddw_gd
            cursor.isNull(offset + 119) ? null : cursor.getString(offset + 119), // sbdw_gd
            cursor.isNull(offset + 120) ? null : cursor.getString(offset + 120), // shsj
            cursor.isNull(offset + 121) ? null : cursor.getString(offset + 121), // sfsch
            cursor.isNull(offset + 122) ? null : cursor.getString(offset + 122), // ed_tag
            cursor.isNull(offset + 123) ? null : cursor.getString(offset + 123), // ljqsl
            cursor.isNull(offset + 124) ? null : cursor.getString(offset + 124), // ljqzzcj
            cursor.isNull(offset + 125) ? null : cursor.getString(offset + 125), // ljqxh
            cursor.isNull(offset + 126) ? null : cursor.getString(offset + 126), // sfjdhzz
            cursor.isNull(offset + 127) ? null : cursor.getString(offset + 127), // sw_id
            cursor.isNull(offset + 128) ? null : cursor.getString(offset + 128) // jy
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BHPZ entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBh(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSbdw(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDddw(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setYcsblx(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCzmc(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setYcsbmc(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDydj(cursor.getLong(offset + 7));
        entity.setZzcj(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setZzcj2(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBhlb(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setBhxh(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setBhxh2(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBhlx(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBhfl(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setScdqjylx(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTdlx(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setBz(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setRjbb(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTyrq(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setDqjyzq(cursor.getFloat(offset + 20));
        entity.setYxdw(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setWhdw(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setSjdw(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setJjdw(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setXlcd(cursor.getFloat(offset + 25));
        entity.setMxts(cursor.getLong(offset + 26));
        entity.setSftcyx(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setTcyxsj(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setCzgldw(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setCzzgdydj(cursor.getLong(offset + 30));
        entity.setBhmc(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setCcrq(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setXcdqjylx(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setBcdqjyrq(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setXcdqjyrq(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setVf(cursor.getInt(offset + 36));
        entity.setScdqjysj(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setSb(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setDdmm(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setScdqjydw(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setCzr(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setWDID(cursor.isNull(offset + 42) ? null : cursor.getLong(offset + 42));
        entity.setCz(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setBhsx(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setSh(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setShr(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setShyy(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setTb(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setBhmcsx(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setSftjyxsj(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setTcyxid(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setZleddy(cursor.getLong(offset + 52));
        entity.setTjr(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setDwtjr(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setZcxz(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setKgbh(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setDycjghrq(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setRjxd(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setDycjxh(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setTyrq2(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setBhlbxh(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setTdlxxh(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setJgmc(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setJglx(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setXcdqjysj(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setSzpg(cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66));
        entity.setZcdw(cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67));
        entity.setJgid(cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68));
        entity.setBdzid(cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69));
        entity.setSjbb(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
        entity.setEdbb(cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71));
        entity.setZqj(cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72));
        entity.setCzsj(cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73));
        entity.setCzpmsid(cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74));
        entity.setJgpmsid(cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75));
        entity.setSb_bhpz_id(cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76));
        entity.setCteceddl(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
        entity.setYxzt(cursor.isNull(offset + 78) ? null : cursor.getString(offset + 78));
        entity.setZcbh(cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79));
        entity.setCcbh(cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80));
        entity.setMntds(cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81));
        entity.setSztds(cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82));
        entity.setSbgnpz(cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83));
        entity.setAkzdm(cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84));
        entity.setAkzdlx(cursor.isNull(offset + 85) ? null : cursor.getString(offset + 85));
        entity.setSsakxtddmm(cursor.isNull(offset + 86) ? null : cursor.getString(offset + 86));
        entity.setBdzlx(cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87));
        entity.setCjxx(cursor.isNull(offset + 88) ? null : cursor.getString(offset + 88));
        entity.setGzlbqlx(cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89));
        entity.setSfjrzz(cursor.isNull(offset + 90) ? null : cursor.getString(offset + 90));
        entity.setCkfs(cursor.isNull(offset + 91) ? null : cursor.getString(offset + 91));
        entity.setSjcjfs(cursor.isNull(offset + 92) ? null : cursor.getString(offset + 92));
        entity.setSbxs(cursor.isNull(offset + 93) ? null : cursor.getString(offset + 93));
        entity.setSfltysb(cursor.isNull(offset + 94) ? null : cursor.getString(offset + 94));
        entity.setLtybzbb(cursor.isNull(offset + 95) ? null : cursor.getString(offset + 95));
        entity.setSfsbm(cursor.isNull(offset + 96) ? null : cursor.getString(offset + 96));
        entity.setSbsj(cursor.isNull(offset + 97) ? null : cursor.getString(offset + 97));
        entity.setUsegddata(cursor.isNull(offset + 98) ? null : cursor.getString(offset + 98));
        entity.setSfbdsj(cursor.isNull(offset + 99) ? null : cursor.getString(offset + 99));
        entity.setBhsbxhxx(cursor.isNull(offset + 100) ? null : cursor.getString(offset + 100));
        entity.setState(cursor.isNull(offset + 101) ? null : cursor.getString(offset + 101));
        entity.setSb_lx_id(cursor.isNull(offset + 102) ? null : cursor.getString(offset + 102));
        entity.setCzsx(cursor.isNull(offset + 103) ? null : cursor.getString(offset + 103));
        entity.setCaseValidate(cursor.isNull(offset + 104) ? null : cursor.getString(offset + 104));
        entity.setHzsj(cursor.isNull(offset + 105) ? null : cursor.getString(offset + 105));
        entity.setLs_validateformat(cursor.isNull(offset + 106) ? null : cursor.getString(offset + 106));
        entity.setSbczlx(cursor.isNull(offset + 107) ? null : cursor.getString(offset + 107));
        entity.setSfxtlr(cursor.isNull(offset + 108) ? null : cursor.getString(offset + 108));
        entity.setShxtlr(cursor.isNull(offset + 109) ? null : cursor.getString(offset + 109));
        entity.setValidateformat(cursor.isNull(offset + 110) ? null : cursor.getString(offset + 110));
        entity.setWj_dw(cursor.isNull(offset + 111) ? null : cursor.getString(offset + 111));
        entity.setWj_ls_id(cursor.isNull(offset + 112) ? null : cursor.getString(offset + 112));
        entity.setXp(cursor.isNull(offset + 113) ? null : cursor.getString(offset + 113));
        entity.setJzxh(cursor.isNull(offset + 114) ? null : cursor.getString(offset + 114));
        entity.setBksl(cursor.getInt(offset + 115));
        entity.setIcdwjmc(cursor.isNull(offset + 116) ? null : cursor.getString(offset + 116));
        entity.setCzgldw_gd(cursor.isNull(offset + 117) ? null : cursor.getString(offset + 117));
        entity.setDddw_gd(cursor.isNull(offset + 118) ? null : cursor.getString(offset + 118));
        entity.setSbdw_gd(cursor.isNull(offset + 119) ? null : cursor.getString(offset + 119));
        entity.setShsj(cursor.isNull(offset + 120) ? null : cursor.getString(offset + 120));
        entity.setSfsch(cursor.isNull(offset + 121) ? null : cursor.getString(offset + 121));
        entity.setEd_tag(cursor.isNull(offset + 122) ? null : cursor.getString(offset + 122));
        entity.setLjqsl(cursor.isNull(offset + 123) ? null : cursor.getString(offset + 123));
        entity.setLjqzzcj(cursor.isNull(offset + 124) ? null : cursor.getString(offset + 124));
        entity.setLjqxh(cursor.isNull(offset + 125) ? null : cursor.getString(offset + 125));
        entity.setSfjdhzz(cursor.isNull(offset + 126) ? null : cursor.getString(offset + 126));
        entity.setSw_id(cursor.isNull(offset + 127) ? null : cursor.getString(offset + 127));
        entity.setJy(cursor.isNull(offset + 128) ? null : cursor.getString(offset + 128));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BHPZ entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BHPZ entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BHPZ entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
