package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.BHPZXHBBGX;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BHPZXHBBGX".
*/
public class BHPZXHBBGXDao extends AbstractDao<BHPZXHBBGX, Long> {

    public static final String TABLENAME = "BHPZXHBBGX";

    /**
     * Properties of entity BHPZXHBBGX.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property BHPZID = new Property(1, long.class, "BHPZID", false, "BHPZID");
        public final static Property RJBBCODE = new Property(2, String.class, "RJBBCODE", false, "RJBBCODE");
        public final static Property SCSJ = new Property(3, String.class, "SCSJ", false, "SCSJ");
        public final static Property SFXTLR = new Property(4, String.class, "SFXTLR", false, "SFXTLR");
    }


    public BHPZXHBBGXDao(DaoConfig config) {
        super(config);
    }
    
    public BHPZXHBBGXDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BHPZXHBBGX entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getBHPZID());
 
        String RJBBCODE = entity.getRJBBCODE();
        if (RJBBCODE != null) {
            stmt.bindString(3, RJBBCODE);
        }
 
        String SCSJ = entity.getSCSJ();
        if (SCSJ != null) {
            stmt.bindString(4, SCSJ);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(5, SFXTLR);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BHPZXHBBGX entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getBHPZID());
 
        String RJBBCODE = entity.getRJBBCODE();
        if (RJBBCODE != null) {
            stmt.bindString(3, RJBBCODE);
        }
 
        String SCSJ = entity.getSCSJ();
        if (SCSJ != null) {
            stmt.bindString(4, SCSJ);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(5, SFXTLR);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BHPZXHBBGX readEntity(Cursor cursor, int offset) {
        BHPZXHBBGX entity = new BHPZXHBBGX( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getLong(offset + 1), // BHPZID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // RJBBCODE
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // SCSJ
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // SFXTLR
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BHPZXHBBGX entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBHPZID(cursor.getLong(offset + 1));
        entity.setRJBBCODE(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSCSJ(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSFXTLR(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BHPZXHBBGX entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BHPZXHBBGX entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BHPZXHBBGX entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
