package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.BHXHRJBB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BHXHRJBB".
*/
public class BHXHRJBBDao extends AbstractDao<BHXHRJBB, Long> {

    public static final String TABLENAME = "BHXHRJBB";

    /**
     * Properties of entity BHXHRJBB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Code = new Property(1, String.class, "code", false, "CODE");
        public final static Property Mkmc = new Property(2, String.class, "mkmc", false, "MKMC");
        public final static Property Bb = new Property(3, String.class, "bb", false, "BB");
        public final static Property Jym = new Property(4, String.class, "jym", false, "JYM");
        public final static Property Sfqy = new Property(5, String.class, "sfqy", false, "SFQY");
        public final static Property Bhxhcode = new Property(6, String.class, "bhxhcode", false, "BHXHCODE");
        public final static Property State = new Property(7, String.class, "state", false, "STATE");
        public final static Property Ms = new Property(8, String.class, "ms", false, "MS");
        public final static Property Bblx = new Property(9, String.class, "bblx", false, "BBLX");
        public final static Property Tbdw = new Property(10, String.class, "tbdw", false, "TBDW");
        public final static Property Tbr = new Property(11, String.class, "tbr", false, "TBR");
        public final static Property Tbsj = new Property(12, String.class, "tbsj", false, "TBSJ");
        public final static Property Bbxx = new Property(13, String.class, "bbxx", false, "BBXX");
        public final static Property Bbxx2 = new Property(14, String.class, "bbxx2", false, "BBXX2");
        public final static Property Cz = new Property(15, String.class, "cz", false, "CZ");
        public final static Property Fg = new Property(16, String.class, "fg", false, "FG");
        public final static Property Fname = new Property(17, String.class, "fname", false, "FNAME");
        public final static Property Ls_code = new Property(18, String.class, "ls_code", false, "LS_CODE");
        public final static Property Ls_rjbbxx = new Property(19, String.class, "ls_rjbbxx", false, "LS_RJBBXX");
        public final static Property Rjbbxx = new Property(20, String.class, "rjbbxx", false, "RJBBXX");
        public final static Property Xx = new Property(21, String.class, "xx", false, "XX");
        public final static Property ED_TAG = new Property(22, String.class, "ED_TAG", false, "ED_TAG");
    }


    public BHXHRJBBDao(DaoConfig config) {
        super(config);
    }
    
    public BHXHRJBBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BHXHRJBB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(2, code);
        }
 
        String mkmc = entity.getMkmc();
        if (mkmc != null) {
            stmt.bindString(3, mkmc);
        }
 
        String bb = entity.getBb();
        if (bb != null) {
            stmt.bindString(4, bb);
        }
 
        String jym = entity.getJym();
        if (jym != null) {
            stmt.bindString(5, jym);
        }
 
        String sfqy = entity.getSfqy();
        if (sfqy != null) {
            stmt.bindString(6, sfqy);
        }
 
        String bhxhcode = entity.getBhxhcode();
        if (bhxhcode != null) {
            stmt.bindString(7, bhxhcode);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(8, state);
        }
 
        String ms = entity.getMs();
        if (ms != null) {
            stmt.bindString(9, ms);
        }
 
        String bblx = entity.getBblx();
        if (bblx != null) {
            stmt.bindString(10, bblx);
        }
 
        String tbdw = entity.getTbdw();
        if (tbdw != null) {
            stmt.bindString(11, tbdw);
        }
 
        String tbr = entity.getTbr();
        if (tbr != null) {
            stmt.bindString(12, tbr);
        }
 
        String tbsj = entity.getTbsj();
        if (tbsj != null) {
            stmt.bindString(13, tbsj);
        }
 
        String bbxx = entity.getBbxx();
        if (bbxx != null) {
            stmt.bindString(14, bbxx);
        }
 
        String bbxx2 = entity.getBbxx2();
        if (bbxx2 != null) {
            stmt.bindString(15, bbxx2);
        }
 
        String cz = entity.getCz();
        if (cz != null) {
            stmt.bindString(16, cz);
        }
 
        String fg = entity.getFg();
        if (fg != null) {
            stmt.bindString(17, fg);
        }
 
        String fname = entity.getFname();
        if (fname != null) {
            stmt.bindString(18, fname);
        }
 
        String ls_code = entity.getLs_code();
        if (ls_code != null) {
            stmt.bindString(19, ls_code);
        }
 
        String ls_rjbbxx = entity.getLs_rjbbxx();
        if (ls_rjbbxx != null) {
            stmt.bindString(20, ls_rjbbxx);
        }
 
        String rjbbxx = entity.getRjbbxx();
        if (rjbbxx != null) {
            stmt.bindString(21, rjbbxx);
        }
 
        String xx = entity.getXx();
        if (xx != null) {
            stmt.bindString(22, xx);
        }
 
        String ED_TAG = entity.getED_TAG();
        if (ED_TAG != null) {
            stmt.bindString(23, ED_TAG);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BHXHRJBB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(2, code);
        }
 
        String mkmc = entity.getMkmc();
        if (mkmc != null) {
            stmt.bindString(3, mkmc);
        }
 
        String bb = entity.getBb();
        if (bb != null) {
            stmt.bindString(4, bb);
        }
 
        String jym = entity.getJym();
        if (jym != null) {
            stmt.bindString(5, jym);
        }
 
        String sfqy = entity.getSfqy();
        if (sfqy != null) {
            stmt.bindString(6, sfqy);
        }
 
        String bhxhcode = entity.getBhxhcode();
        if (bhxhcode != null) {
            stmt.bindString(7, bhxhcode);
        }
 
        String state = entity.getState();
        if (state != null) {
            stmt.bindString(8, state);
        }
 
        String ms = entity.getMs();
        if (ms != null) {
            stmt.bindString(9, ms);
        }
 
        String bblx = entity.getBblx();
        if (bblx != null) {
            stmt.bindString(10, bblx);
        }
 
        String tbdw = entity.getTbdw();
        if (tbdw != null) {
            stmt.bindString(11, tbdw);
        }
 
        String tbr = entity.getTbr();
        if (tbr != null) {
            stmt.bindString(12, tbr);
        }
 
        String tbsj = entity.getTbsj();
        if (tbsj != null) {
            stmt.bindString(13, tbsj);
        }
 
        String bbxx = entity.getBbxx();
        if (bbxx != null) {
            stmt.bindString(14, bbxx);
        }
 
        String bbxx2 = entity.getBbxx2();
        if (bbxx2 != null) {
            stmt.bindString(15, bbxx2);
        }
 
        String cz = entity.getCz();
        if (cz != null) {
            stmt.bindString(16, cz);
        }
 
        String fg = entity.getFg();
        if (fg != null) {
            stmt.bindString(17, fg);
        }
 
        String fname = entity.getFname();
        if (fname != null) {
            stmt.bindString(18, fname);
        }
 
        String ls_code = entity.getLs_code();
        if (ls_code != null) {
            stmt.bindString(19, ls_code);
        }
 
        String ls_rjbbxx = entity.getLs_rjbbxx();
        if (ls_rjbbxx != null) {
            stmt.bindString(20, ls_rjbbxx);
        }
 
        String rjbbxx = entity.getRjbbxx();
        if (rjbbxx != null) {
            stmt.bindString(21, rjbbxx);
        }
 
        String xx = entity.getXx();
        if (xx != null) {
            stmt.bindString(22, xx);
        }
 
        String ED_TAG = entity.getED_TAG();
        if (ED_TAG != null) {
            stmt.bindString(23, ED_TAG);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BHXHRJBB readEntity(Cursor cursor, int offset) {
        BHXHRJBB entity = new BHXHRJBB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // code
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mkmc
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bb
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // jym
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sfqy
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bhxhcode
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // state
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ms
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // bblx
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // tbdw
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // tbr
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // tbsj
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // bbxx
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // bbxx2
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // cz
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // fg
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // fname
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // ls_code
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // ls_rjbbxx
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // rjbbxx
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // xx
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22) // ED_TAG
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BHXHRJBB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMkmc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBb(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJym(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSfqy(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBhxhcode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setState(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setMs(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBblx(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTbdw(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTbr(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTbsj(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBbxx(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBbxx2(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCz(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setFg(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setFname(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setLs_code(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setLs_rjbbxx(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setRjbbxx(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setXx(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setED_TAG(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BHXHRJBB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BHXHRJBB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BHXHRJBB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
