package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.ycsb.BYQCS;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BYQCS".
*/
public class BYQCSDao extends AbstractDao<BYQCS, Long> {

    public static final String TABLENAME = "BYQCS";

    /**
     * Properties of entity BYQCS.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property BH = new Property(1, String.class, "BH", false, "BH");
        public final static Property BYQMC = new Property(2, String.class, "BYQMC", false, "BYQMC");
        public final static Property KGBH = new Property(3, String.class, "KGBH", false, "KGBH");
        public final static Property DYDJ = new Property(4, int.class, "DYDJ", false, "DYDJ");
        public final static Property CZMC = new Property(5, String.class, "CZMC", false, "CZMC");
        public final static Property SFFBZ = new Property(6, String.class, "SFFBZ", false, "SFFBZ");
        public final static Property FDJMC = new Property(7, String.class, "FDJMC", false, "FDJMC");
        public final static Property SFTCYX = new Property(8, String.class, "SFTCYX", false, "SFTCYX");
        public final static Property BZ = new Property(9, String.class, "BZ", false, "BZ");
        public final static Property Sh = new Property(10, String.class, "sh", false, "SH");
        public final static Property Shr2 = new Property(11, String.class, "shr2", false, "SHR");
        public final static Property Shyy = new Property(12, String.class, "shyy", false, "SHYY");
        public final static Property GLDW = new Property(13, String.class, "GLDW", false, "GLDW");
        public final static Property Vf = new Property(14, int.class, "vf", false, "VF");
        public final static Property Czr = new Property(15, String.class, "czr", false, "CZR");
        public final static Property Tjr = new Property(16, String.class, "tjr", false, "TJR");
        public final static Property Dwtjr = new Property(17, String.class, "dwtjr", false, "DWTJR");
        public final static Property WDID = new Property(18, int.class, "WDID", false, "WDID");
        public final static Property BYQXH = new Property(19, String.class, "BYQXH", false, "BYQXH");
        public final static Property Dddw = new Property(20, String.class, "dddw", false, "DDDW");
        public final static Property Jglx = new Property(21, String.class, "jglx", false, "JGLX");
        public final static Property Jgmc = new Property(22, String.class, "jgmc", false, "JGMC");
        public final static Property CZSJ = new Property(23, java.util.Date.class, "CZSJ", false, "CZSJ");
        public final static Property FDJJGLX = new Property(24, String.class, "FDJJGLX", false, "FDJJGLX");
        public final static Property FDJJGMC = new Property(25, String.class, "FDJJGMC", false, "FDJJGMC");
        public final static Property SFBDSJ = new Property(26, String.class, "SFBDSJ", false, "SFBDSJ");
        public final static Property SB = new Property(27, String.class, "SB", false, "SB");
        public final static Property SBSJ = new Property(28, java.util.Date.class, "SBSJ", false, "SBSJ");
        public final static Property SB_LS_ID = new Property(29, String.class, "SB_LS_ID", false, "SB_LS_ID");
        public final static Property SBDW = new Property(30, String.class, "SBDW", false, "SBDW");
        public final static Property HZSJ = new Property(31, java.util.Date.class, "HZSJ", false, "HZSJ");
        public final static Property SBCZLX = new Property(32, String.class, "SBCZLX", false, "SBCZLX");
        public final static Property SFXTLR = new Property(33, String.class, "SFXTLR", false, "SFXTLR");
        public final static Property WJ_DW = new Property(34, String.class, "WJ_DW", false, "WJ_DW");
        public final static Property WJ_LS_ID = new Property(35, String.class, "WJ_LS_ID", false, "WJ_LS_ID");
    }


    public BYQCSDao(DaoConfig config) {
        super(config);
    }
    
    public BYQCSDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BYQCS entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String BH = entity.getBH();
        if (BH != null) {
            stmt.bindString(2, BH);
        }
 
        String BYQMC = entity.getBYQMC();
        if (BYQMC != null) {
            stmt.bindString(3, BYQMC);
        }
 
        String KGBH = entity.getKGBH();
        if (KGBH != null) {
            stmt.bindString(4, KGBH);
        }
        stmt.bindLong(5, entity.getDYDJ());
 
        String CZMC = entity.getCZMC();
        if (CZMC != null) {
            stmt.bindString(6, CZMC);
        }
 
        String SFFBZ = entity.getSFFBZ();
        if (SFFBZ != null) {
            stmt.bindString(7, SFFBZ);
        }
 
        String FDJMC = entity.getFDJMC();
        if (FDJMC != null) {
            stmt.bindString(8, FDJMC);
        }
 
        String SFTCYX = entity.getSFTCYX();
        if (SFTCYX != null) {
            stmt.bindString(9, SFTCYX);
        }
 
        String BZ = entity.getBZ();
        if (BZ != null) {
            stmt.bindString(10, BZ);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(11, sh);
        }
 
        String shr2 = entity.getShr2();
        if (shr2 != null) {
            stmt.bindString(12, shr2);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(13, shyy);
        }
 
        String GLDW = entity.getGLDW();
        if (GLDW != null) {
            stmt.bindString(14, GLDW);
        }
        stmt.bindLong(15, entity.getVf());
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(16, czr);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(17, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(18, dwtjr);
        }
        stmt.bindLong(19, entity.getWDID());
 
        String BYQXH = entity.getBYQXH();
        if (BYQXH != null) {
            stmt.bindString(20, BYQXH);
        }
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(21, dddw);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(22, jglx);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(23, jgmc);
        }
 
        java.util.Date CZSJ = entity.getCZSJ();
        if (CZSJ != null) {
            stmt.bindLong(24, CZSJ.getTime());
        }
 
        String FDJJGLX = entity.getFDJJGLX();
        if (FDJJGLX != null) {
            stmt.bindString(25, FDJJGLX);
        }
 
        String FDJJGMC = entity.getFDJJGMC();
        if (FDJJGMC != null) {
            stmt.bindString(26, FDJJGMC);
        }
 
        String SFBDSJ = entity.getSFBDSJ();
        if (SFBDSJ != null) {
            stmt.bindString(27, SFBDSJ);
        }
 
        String SB = entity.getSB();
        if (SB != null) {
            stmt.bindString(28, SB);
        }
 
        java.util.Date SBSJ = entity.getSBSJ();
        if (SBSJ != null) {
            stmt.bindLong(29, SBSJ.getTime());
        }
 
        String SB_LS_ID = entity.getSB_LS_ID();
        if (SB_LS_ID != null) {
            stmt.bindString(30, SB_LS_ID);
        }
 
        String SBDW = entity.getSBDW();
        if (SBDW != null) {
            stmt.bindString(31, SBDW);
        }
 
        java.util.Date HZSJ = entity.getHZSJ();
        if (HZSJ != null) {
            stmt.bindLong(32, HZSJ.getTime());
        }
 
        String SBCZLX = entity.getSBCZLX();
        if (SBCZLX != null) {
            stmt.bindString(33, SBCZLX);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(34, SFXTLR);
        }
 
        String WJ_DW = entity.getWJ_DW();
        if (WJ_DW != null) {
            stmt.bindString(35, WJ_DW);
        }
 
        String WJ_LS_ID = entity.getWJ_LS_ID();
        if (WJ_LS_ID != null) {
            stmt.bindString(36, WJ_LS_ID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BYQCS entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String BH = entity.getBH();
        if (BH != null) {
            stmt.bindString(2, BH);
        }
 
        String BYQMC = entity.getBYQMC();
        if (BYQMC != null) {
            stmt.bindString(3, BYQMC);
        }
 
        String KGBH = entity.getKGBH();
        if (KGBH != null) {
            stmt.bindString(4, KGBH);
        }
        stmt.bindLong(5, entity.getDYDJ());
 
        String CZMC = entity.getCZMC();
        if (CZMC != null) {
            stmt.bindString(6, CZMC);
        }
 
        String SFFBZ = entity.getSFFBZ();
        if (SFFBZ != null) {
            stmt.bindString(7, SFFBZ);
        }
 
        String FDJMC = entity.getFDJMC();
        if (FDJMC != null) {
            stmt.bindString(8, FDJMC);
        }
 
        String SFTCYX = entity.getSFTCYX();
        if (SFTCYX != null) {
            stmt.bindString(9, SFTCYX);
        }
 
        String BZ = entity.getBZ();
        if (BZ != null) {
            stmt.bindString(10, BZ);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(11, sh);
        }
 
        String shr2 = entity.getShr2();
        if (shr2 != null) {
            stmt.bindString(12, shr2);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(13, shyy);
        }
 
        String GLDW = entity.getGLDW();
        if (GLDW != null) {
            stmt.bindString(14, GLDW);
        }
        stmt.bindLong(15, entity.getVf());
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(16, czr);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(17, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(18, dwtjr);
        }
        stmt.bindLong(19, entity.getWDID());
 
        String BYQXH = entity.getBYQXH();
        if (BYQXH != null) {
            stmt.bindString(20, BYQXH);
        }
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(21, dddw);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(22, jglx);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(23, jgmc);
        }
 
        java.util.Date CZSJ = entity.getCZSJ();
        if (CZSJ != null) {
            stmt.bindLong(24, CZSJ.getTime());
        }
 
        String FDJJGLX = entity.getFDJJGLX();
        if (FDJJGLX != null) {
            stmt.bindString(25, FDJJGLX);
        }
 
        String FDJJGMC = entity.getFDJJGMC();
        if (FDJJGMC != null) {
            stmt.bindString(26, FDJJGMC);
        }
 
        String SFBDSJ = entity.getSFBDSJ();
        if (SFBDSJ != null) {
            stmt.bindString(27, SFBDSJ);
        }
 
        String SB = entity.getSB();
        if (SB != null) {
            stmt.bindString(28, SB);
        }
 
        java.util.Date SBSJ = entity.getSBSJ();
        if (SBSJ != null) {
            stmt.bindLong(29, SBSJ.getTime());
        }
 
        String SB_LS_ID = entity.getSB_LS_ID();
        if (SB_LS_ID != null) {
            stmt.bindString(30, SB_LS_ID);
        }
 
        String SBDW = entity.getSBDW();
        if (SBDW != null) {
            stmt.bindString(31, SBDW);
        }
 
        java.util.Date HZSJ = entity.getHZSJ();
        if (HZSJ != null) {
            stmt.bindLong(32, HZSJ.getTime());
        }
 
        String SBCZLX = entity.getSBCZLX();
        if (SBCZLX != null) {
            stmt.bindString(33, SBCZLX);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(34, SFXTLR);
        }
 
        String WJ_DW = entity.getWJ_DW();
        if (WJ_DW != null) {
            stmt.bindString(35, WJ_DW);
        }
 
        String WJ_LS_ID = entity.getWJ_LS_ID();
        if (WJ_LS_ID != null) {
            stmt.bindString(36, WJ_LS_ID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BYQCS readEntity(Cursor cursor, int offset) {
        BYQCS entity = new BYQCS( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // BH
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // BYQMC
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // KGBH
            cursor.getInt(offset + 4), // DYDJ
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // CZMC
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // SFFBZ
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // FDJMC
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // SFTCYX
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // BZ
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // sh
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // shr2
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // shyy
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // GLDW
            cursor.getInt(offset + 14), // vf
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // czr
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tjr
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // dwtjr
            cursor.getInt(offset + 18), // WDID
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // BYQXH
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // dddw
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // jglx
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // jgmc
            cursor.isNull(offset + 23) ? null : new java.util.Date(cursor.getLong(offset + 23)), // CZSJ
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // FDJJGLX
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // FDJJGMC
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // SFBDSJ
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // SB
            cursor.isNull(offset + 28) ? null : new java.util.Date(cursor.getLong(offset + 28)), // SBSJ
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // SB_LS_ID
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // SBDW
            cursor.isNull(offset + 31) ? null : new java.util.Date(cursor.getLong(offset + 31)), // HZSJ
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // SBCZLX
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // SFXTLR
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // WJ_DW
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35) // WJ_LS_ID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BYQCS entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBH(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBYQMC(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setKGBH(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDYDJ(cursor.getInt(offset + 4));
        entity.setCZMC(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSFFBZ(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFDJMC(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSFTCYX(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBZ(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSh(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setShr2(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setShyy(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setGLDW(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setVf(cursor.getInt(offset + 14));
        entity.setCzr(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTjr(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setDwtjr(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setWDID(cursor.getInt(offset + 18));
        entity.setBYQXH(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setDddw(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setJglx(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setJgmc(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setCZSJ(cursor.isNull(offset + 23) ? null : new java.util.Date(cursor.getLong(offset + 23)));
        entity.setFDJJGLX(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setFDJJGMC(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setSFBDSJ(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setSB(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setSBSJ(cursor.isNull(offset + 28) ? null : new java.util.Date(cursor.getLong(offset + 28)));
        entity.setSB_LS_ID(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setSBDW(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setHZSJ(cursor.isNull(offset + 31) ? null : new java.util.Date(cursor.getLong(offset + 31)));
        entity.setSBCZLX(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setSFXTLR(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setWJ_DW(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setWJ_LS_ID(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BYQCS entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BYQCS entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BYQCS entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
