package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.ycsb.CZCS;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CZCS".
*/
public class CZCSDao extends AbstractDao<CZCS, Long> {

    public static final String TABLENAME = "CZCS";

    /**
     * Properties of entity CZCS.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Bh = new Property(1, String.class, "bh", false, "BH");
        public final static Property Czmc = new Property(2, String.class, "czmc", false, "CZMC");
        public final static Property Czzgdydj = new Property(3, long.class, "czzgdydj", false, "CZZGDYDJ");
        public final static Property Bz = new Property(4, String.class, "bz", false, "BZ");
        public final static Property Gldw = new Property(5, String.class, "gldw", false, "GLDW");
        public final static Property Vf = new Property(6, int.class, "vf", false, "VF");
        public final static Property Czr = new Property(7, String.class, "czr", false, "CZR");
        public final static Property WDID = new Property(8, int.class, "WDID", false, "WDID");
        public final static Property Czszdq = new Property(9, String.class, "czszdq", false, "CZSZDQ");
        public final static Property Tyrq = new Property(10, java.util.Date.class, "tyrq", false, "TYRQ");
        public final static Property Bdzlx = new Property(11, String.class, "bdzlx", false, "BDZLX");
        public final static Property Czsj = new Property(12, java.util.Date.class, "czsj", false, "CZSJ");
        public final static Property Objid = new Property(13, String.class, "objid", false, "OBJID");
        public final static Property Sftcyx = new Property(14, String.class, "sftcyx", false, "SFTCYX");
        public final static Property Tcyxsj = new Property(15, java.util.Date.class, "tcyxsj", false, "TCYXSJ");
        public final static Property Shyy = new Property(16, String.class, "shyy", false, "SHYY");
        public final static Property Tjr = new Property(17, String.class, "tjr", false, "TJR");
        public final static Property Shr = new Property(18, String.class, "shr", false, "SHR");
        public final static Property Sh = new Property(19, String.class, "sh", false, "SH");
        public final static Property Sfbdsj = new Property(20, String.class, "sfbdsj", false, "SFBDSJ");
        public final static Property Sb = new Property(21, String.class, "sb", false, "SB");
        public final static Property Sbsj = new Property(22, java.util.Date.class, "sbsj", false, "SBSJ");
        public final static Property Sb_ls_id = new Property(23, String.class, "sb_ls_id", false, "SB_LS_ID");
        public final static Property Sbdw = new Property(24, String.class, "sbdw", false, "SBDW");
        public final static Property Czsx = new Property(25, String.class, "czsx", false, "CZSX");
        public final static Property Hzsj = new Property(26, java.util.Date.class, "hzsj", false, "HZSJ");
        public final static Property Sbczlx = new Property(27, String.class, "sbczlx", false, "SBCZLX");
        public final static Property Sfxtlr = new Property(28, String.class, "sfxtlr", false, "SFXTLR");
        public final static Property Wj_dw = new Property(29, String.class, "wj_dw", false, "WJ_DW");
        public final static Property Wj_ls_id = new Property(30, String.class, "wj_ls_id", false, "WJ_LS_ID");
        public final static Property Isfhz = new Property(31, String.class, "isfhz", false, "ISFHZ");
    }


    public CZCSDao(DaoConfig config) {
        super(config);
    }
    
    public CZCSDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CZCS entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bh = entity.getBh();
        if (bh != null) {
            stmt.bindString(2, bh);
        }
 
        String czmc = entity.getCzmc();
        if (czmc != null) {
            stmt.bindString(3, czmc);
        }
        stmt.bindLong(4, entity.getCzzgdydj());
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(5, bz);
        }
 
        String gldw = entity.getGldw();
        if (gldw != null) {
            stmt.bindString(6, gldw);
        }
        stmt.bindLong(7, entity.getVf());
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(8, czr);
        }
        stmt.bindLong(9, entity.getWDID());
 
        String czszdq = entity.getCzszdq();
        if (czszdq != null) {
            stmt.bindString(10, czszdq);
        }
 
        java.util.Date tyrq = entity.getTyrq();
        if (tyrq != null) {
            stmt.bindLong(11, tyrq.getTime());
        }
 
        String bdzlx = entity.getBdzlx();
        if (bdzlx != null) {
            stmt.bindString(12, bdzlx);
        }
 
        java.util.Date czsj = entity.getCzsj();
        if (czsj != null) {
            stmt.bindLong(13, czsj.getTime());
        }
 
        String objid = entity.getObjid();
        if (objid != null) {
            stmt.bindString(14, objid);
        }
 
        String sftcyx = entity.getSftcyx();
        if (sftcyx != null) {
            stmt.bindString(15, sftcyx);
        }
 
        java.util.Date tcyxsj = entity.getTcyxsj();
        if (tcyxsj != null) {
            stmt.bindLong(16, tcyxsj.getTime());
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(17, shyy);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(18, tjr);
        }
 
        String shr = entity.getShr();
        if (shr != null) {
            stmt.bindString(19, shr);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(20, sh);
        }
 
        String sfbdsj = entity.getSfbdsj();
        if (sfbdsj != null) {
            stmt.bindString(21, sfbdsj);
        }
 
        String sb = entity.getSb();
        if (sb != null) {
            stmt.bindString(22, sb);
        }
 
        java.util.Date sbsj = entity.getSbsj();
        if (sbsj != null) {
            stmt.bindLong(23, sbsj.getTime());
        }
 
        String sb_ls_id = entity.getSb_ls_id();
        if (sb_ls_id != null) {
            stmt.bindString(24, sb_ls_id);
        }
 
        String sbdw = entity.getSbdw();
        if (sbdw != null) {
            stmt.bindString(25, sbdw);
        }
 
        String czsx = entity.getCzsx();
        if (czsx != null) {
            stmt.bindString(26, czsx);
        }
 
        java.util.Date hzsj = entity.getHzsj();
        if (hzsj != null) {
            stmt.bindLong(27, hzsj.getTime());
        }
 
        String sbczlx = entity.getSbczlx();
        if (sbczlx != null) {
            stmt.bindString(28, sbczlx);
        }
 
        String sfxtlr = entity.getSfxtlr();
        if (sfxtlr != null) {
            stmt.bindString(29, sfxtlr);
        }
 
        String wj_dw = entity.getWj_dw();
        if (wj_dw != null) {
            stmt.bindString(30, wj_dw);
        }
 
        String wj_ls_id = entity.getWj_ls_id();
        if (wj_ls_id != null) {
            stmt.bindString(31, wj_ls_id);
        }
 
        String isfhz = entity.getIsfhz();
        if (isfhz != null) {
            stmt.bindString(32, isfhz);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CZCS entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bh = entity.getBh();
        if (bh != null) {
            stmt.bindString(2, bh);
        }
 
        String czmc = entity.getCzmc();
        if (czmc != null) {
            stmt.bindString(3, czmc);
        }
        stmt.bindLong(4, entity.getCzzgdydj());
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(5, bz);
        }
 
        String gldw = entity.getGldw();
        if (gldw != null) {
            stmt.bindString(6, gldw);
        }
        stmt.bindLong(7, entity.getVf());
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(8, czr);
        }
        stmt.bindLong(9, entity.getWDID());
 
        String czszdq = entity.getCzszdq();
        if (czszdq != null) {
            stmt.bindString(10, czszdq);
        }
 
        java.util.Date tyrq = entity.getTyrq();
        if (tyrq != null) {
            stmt.bindLong(11, tyrq.getTime());
        }
 
        String bdzlx = entity.getBdzlx();
        if (bdzlx != null) {
            stmt.bindString(12, bdzlx);
        }
 
        java.util.Date czsj = entity.getCzsj();
        if (czsj != null) {
            stmt.bindLong(13, czsj.getTime());
        }
 
        String objid = entity.getObjid();
        if (objid != null) {
            stmt.bindString(14, objid);
        }
 
        String sftcyx = entity.getSftcyx();
        if (sftcyx != null) {
            stmt.bindString(15, sftcyx);
        }
 
        java.util.Date tcyxsj = entity.getTcyxsj();
        if (tcyxsj != null) {
            stmt.bindLong(16, tcyxsj.getTime());
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(17, shyy);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(18, tjr);
        }
 
        String shr = entity.getShr();
        if (shr != null) {
            stmt.bindString(19, shr);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(20, sh);
        }
 
        String sfbdsj = entity.getSfbdsj();
        if (sfbdsj != null) {
            stmt.bindString(21, sfbdsj);
        }
 
        String sb = entity.getSb();
        if (sb != null) {
            stmt.bindString(22, sb);
        }
 
        java.util.Date sbsj = entity.getSbsj();
        if (sbsj != null) {
            stmt.bindLong(23, sbsj.getTime());
        }
 
        String sb_ls_id = entity.getSb_ls_id();
        if (sb_ls_id != null) {
            stmt.bindString(24, sb_ls_id);
        }
 
        String sbdw = entity.getSbdw();
        if (sbdw != null) {
            stmt.bindString(25, sbdw);
        }
 
        String czsx = entity.getCzsx();
        if (czsx != null) {
            stmt.bindString(26, czsx);
        }
 
        java.util.Date hzsj = entity.getHzsj();
        if (hzsj != null) {
            stmt.bindLong(27, hzsj.getTime());
        }
 
        String sbczlx = entity.getSbczlx();
        if (sbczlx != null) {
            stmt.bindString(28, sbczlx);
        }
 
        String sfxtlr = entity.getSfxtlr();
        if (sfxtlr != null) {
            stmt.bindString(29, sfxtlr);
        }
 
        String wj_dw = entity.getWj_dw();
        if (wj_dw != null) {
            stmt.bindString(30, wj_dw);
        }
 
        String wj_ls_id = entity.getWj_ls_id();
        if (wj_ls_id != null) {
            stmt.bindString(31, wj_ls_id);
        }
 
        String isfhz = entity.getIsfhz();
        if (isfhz != null) {
            stmt.bindString(32, isfhz);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CZCS readEntity(Cursor cursor, int offset) {
        CZCS entity = new CZCS( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bh
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // czmc
            cursor.getLong(offset + 3), // czzgdydj
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bz
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // gldw
            cursor.getInt(offset + 6), // vf
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // czr
            cursor.getInt(offset + 8), // WDID
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // czszdq
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // tyrq
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // bdzlx
            cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)), // czsj
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // objid
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // sftcyx
            cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)), // tcyxsj
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // shyy
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // tjr
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // shr
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // sh
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // sfbdsj
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // sb
            cursor.isNull(offset + 22) ? null : new java.util.Date(cursor.getLong(offset + 22)), // sbsj
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // sb_ls_id
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // sbdw
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // czsx
            cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)), // hzsj
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // sbczlx
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // sfxtlr
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // wj_dw
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // wj_ls_id
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31) // isfhz
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CZCS entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBh(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCzmc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCzzgdydj(cursor.getLong(offset + 3));
        entity.setBz(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGldw(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setVf(cursor.getInt(offset + 6));
        entity.setCzr(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWDID(cursor.getInt(offset + 8));
        entity.setCzszdq(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTyrq(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setBdzlx(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCzsj(cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)));
        entity.setObjid(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setSftcyx(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setTcyxsj(cursor.isNull(offset + 15) ? null : new java.util.Date(cursor.getLong(offset + 15)));
        entity.setShyy(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTjr(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setShr(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setSh(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setSfbdsj(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setSb(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setSbsj(cursor.isNull(offset + 22) ? null : new java.util.Date(cursor.getLong(offset + 22)));
        entity.setSb_ls_id(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setSbdw(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setCzsx(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setHzsj(cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)));
        entity.setSbczlx(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setSfxtlr(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setWj_dw(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setWj_ls_id(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setIsfhz(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CZCS entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CZCS entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CZCS entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
