package cn.com.sgcc.dev.dao2;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.com.sgcc.dev.model2.DWLX;
import cn.com.sgcc.dev.model2.JZXH;
import cn.com.sgcc.dev.model2.AKXT;
import cn.com.sgcc.dev.model2.ZZCJ;
import cn.com.sgcc.dev.model2.BZSJFL;
import cn.com.sgcc.dev.model2.CCXX;
import cn.com.sgcc.dev.model2.AKXTGX;
import cn.com.sgcc.dev.model2.SBXX;
import cn.com.sgcc.dev.model2.FZBHSB;
import cn.com.sgcc.dev.model2.CCXXBK;
import cn.com.sgcc.dev.model2.RZGL;
import cn.com.sgcc.dev.model2.CCXXRJBB;
import cn.com.sgcc.dev.model2.BKXX;
import cn.com.sgcc.dev.model2.SBZCXX;
import cn.com.sgcc.dev.model2.BZSJ;
import cn.com.sgcc.dev.model2.LJQXX;
import cn.com.sgcc.dev.model2.ycsb.JGCS;
import cn.com.sgcc.dev.model2.ycsb.MXCS;
import cn.com.sgcc.dev.model2.ycsb.DKQCS;
import cn.com.sgcc.dev.model2.ycsb.XLCS;
import cn.com.sgcc.dev.model2.ycsb.DDJCS;
import cn.com.sgcc.dev.model2.ycsb.DRQCS;
import cn.com.sgcc.dev.model2.ycsb.BYQCS;
import cn.com.sgcc.dev.model2.ycsb.FDJCS;
import cn.com.sgcc.dev.model2.ycsb.CZCS;
import cn.com.sgcc.dev.model2.ycsb.DLQCS;
import cn.com.sgcc.dev.model2.UserInfo;
import cn.com.sgcc.dev.model2.TDXX;
import cn.com.sgcc.dev.model2.PZTDGX;
import cn.com.sgcc.dev.model2.BHLBXH;
import cn.com.sgcc.dev.model2.LTYSBXH;
import cn.com.sgcc.dev.model2.BDW;
import cn.com.sgcc.dev.model2.CODE;
import cn.com.sgcc.dev.model2.BHSBXHB;
import cn.com.sgcc.dev.model2.BHPZ;
import cn.com.sgcc.dev.model2.WDGL;
import cn.com.sgcc.dev.model2.BHPZXHBBGX;
import cn.com.sgcc.dev.model2.DLQK;
import cn.com.sgcc.dev.model2.GXDW;
import cn.com.sgcc.dev.model2.FZBHSBXHBBGX;
import cn.com.sgcc.dev.model2.RLST_USER;
import cn.com.sgcc.dev.model2.ICDXX;
import cn.com.sgcc.dev.model2.DWJC;
import cn.com.sgcc.dev.model2.BHXHRJBB;

import cn.com.sgcc.dev.dao2.DWLXDao;
import cn.com.sgcc.dev.dao2.JZXHDao;
import cn.com.sgcc.dev.dao2.AKXTDao;
import cn.com.sgcc.dev.dao2.ZZCJDao;
import cn.com.sgcc.dev.dao2.BZSJFLDao;
import cn.com.sgcc.dev.dao2.CCXXDao;
import cn.com.sgcc.dev.dao2.AKXTGXDao;
import cn.com.sgcc.dev.dao2.SBXXDao;
import cn.com.sgcc.dev.dao2.FZBHSBDao;
import cn.com.sgcc.dev.dao2.CCXXBKDao;
import cn.com.sgcc.dev.dao2.RZGLDao;
import cn.com.sgcc.dev.dao2.CCXXRJBBDao;
import cn.com.sgcc.dev.dao2.BKXXDao;
import cn.com.sgcc.dev.dao2.SBZCXXDao;
import cn.com.sgcc.dev.dao2.BZSJDao;
import cn.com.sgcc.dev.dao2.LJQXXDao;
import cn.com.sgcc.dev.dao2.JGCSDao;
import cn.com.sgcc.dev.dao2.MXCSDao;
import cn.com.sgcc.dev.dao2.DKQCSDao;
import cn.com.sgcc.dev.dao2.XLCSDao;
import cn.com.sgcc.dev.dao2.DDJCSDao;
import cn.com.sgcc.dev.dao2.DRQCSDao;
import cn.com.sgcc.dev.dao2.BYQCSDao;
import cn.com.sgcc.dev.dao2.FDJCSDao;
import cn.com.sgcc.dev.dao2.CZCSDao;
import cn.com.sgcc.dev.dao2.DLQCSDao;
import cn.com.sgcc.dev.dao2.UserInfoDao;
import cn.com.sgcc.dev.dao2.TDXXDao;
import cn.com.sgcc.dev.dao2.PZTDGXDao;
import cn.com.sgcc.dev.dao2.BHLBXHDao;
import cn.com.sgcc.dev.dao2.LTYSBXHDao;
import cn.com.sgcc.dev.dao2.BDWDao;
import cn.com.sgcc.dev.dao2.CODEDao;
import cn.com.sgcc.dev.dao2.BHSBXHBDao;
import cn.com.sgcc.dev.dao2.BHPZDao;
import cn.com.sgcc.dev.dao2.WDGLDao;
import cn.com.sgcc.dev.dao2.BHPZXHBBGXDao;
import cn.com.sgcc.dev.dao2.DLQKDao;
import cn.com.sgcc.dev.dao2.GXDWDao;
import cn.com.sgcc.dev.dao2.FZBHSBXHBBGXDao;
import cn.com.sgcc.dev.dao2.RLST_USERDao;
import cn.com.sgcc.dev.dao2.ICDXXDao;
import cn.com.sgcc.dev.dao2.DWJCDao;
import cn.com.sgcc.dev.dao2.BHXHRJBBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dWLXDaoConfig;
    private final DaoConfig jZXHDaoConfig;
    private final DaoConfig aKXTDaoConfig;
    private final DaoConfig zZCJDaoConfig;
    private final DaoConfig bZSJFLDaoConfig;
    private final DaoConfig cCXXDaoConfig;
    private final DaoConfig aKXTGXDaoConfig;
    private final DaoConfig sBXXDaoConfig;
    private final DaoConfig fZBHSBDaoConfig;
    private final DaoConfig cCXXBKDaoConfig;
    private final DaoConfig rZGLDaoConfig;
    private final DaoConfig cCXXRJBBDaoConfig;
    private final DaoConfig bKXXDaoConfig;
    private final DaoConfig sBZCXXDaoConfig;
    private final DaoConfig bZSJDaoConfig;
    private final DaoConfig lJQXXDaoConfig;
    private final DaoConfig jGCSDaoConfig;
    private final DaoConfig mXCSDaoConfig;
    private final DaoConfig dKQCSDaoConfig;
    private final DaoConfig xLCSDaoConfig;
    private final DaoConfig dDJCSDaoConfig;
    private final DaoConfig dRQCSDaoConfig;
    private final DaoConfig bYQCSDaoConfig;
    private final DaoConfig fDJCSDaoConfig;
    private final DaoConfig cZCSDaoConfig;
    private final DaoConfig dLQCSDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig tDXXDaoConfig;
    private final DaoConfig pZTDGXDaoConfig;
    private final DaoConfig bHLBXHDaoConfig;
    private final DaoConfig lTYSBXHDaoConfig;
    private final DaoConfig bDWDaoConfig;
    private final DaoConfig cODEDaoConfig;
    private final DaoConfig bHSBXHBDaoConfig;
    private final DaoConfig bHPZDaoConfig;
    private final DaoConfig wDGLDaoConfig;
    private final DaoConfig bHPZXHBBGXDaoConfig;
    private final DaoConfig dLQKDaoConfig;
    private final DaoConfig gXDWDaoConfig;
    private final DaoConfig fZBHSBXHBBGXDaoConfig;
    private final DaoConfig rLST_USERDaoConfig;
    private final DaoConfig iCDXXDaoConfig;
    private final DaoConfig dWJCDaoConfig;
    private final DaoConfig bHXHRJBBDaoConfig;

    private final DWLXDao dWLXDao;
    private final JZXHDao jZXHDao;
    private final AKXTDao aKXTDao;
    private final ZZCJDao zZCJDao;
    private final BZSJFLDao bZSJFLDao;
    private final CCXXDao cCXXDao;
    private final AKXTGXDao aKXTGXDao;
    private final SBXXDao sBXXDao;
    private final FZBHSBDao fZBHSBDao;
    private final CCXXBKDao cCXXBKDao;
    private final RZGLDao rZGLDao;
    private final CCXXRJBBDao cCXXRJBBDao;
    private final BKXXDao bKXXDao;
    private final SBZCXXDao sBZCXXDao;
    private final BZSJDao bZSJDao;
    private final LJQXXDao lJQXXDao;
    private final JGCSDao jGCSDao;
    private final MXCSDao mXCSDao;
    private final DKQCSDao dKQCSDao;
    private final XLCSDao xLCSDao;
    private final DDJCSDao dDJCSDao;
    private final DRQCSDao dRQCSDao;
    private final BYQCSDao bYQCSDao;
    private final FDJCSDao fDJCSDao;
    private final CZCSDao cZCSDao;
    private final DLQCSDao dLQCSDao;
    private final UserInfoDao userInfoDao;
    private final TDXXDao tDXXDao;
    private final PZTDGXDao pZTDGXDao;
    private final BHLBXHDao bHLBXHDao;
    private final LTYSBXHDao lTYSBXHDao;
    private final BDWDao bDWDao;
    private final CODEDao cODEDao;
    private final BHSBXHBDao bHSBXHBDao;
    private final BHPZDao bHPZDao;
    private final WDGLDao wDGLDao;
    private final BHPZXHBBGXDao bHPZXHBBGXDao;
    private final DLQKDao dLQKDao;
    private final GXDWDao gXDWDao;
    private final FZBHSBXHBBGXDao fZBHSBXHBBGXDao;
    private final RLST_USERDao rLST_USERDao;
    private final ICDXXDao iCDXXDao;
    private final DWJCDao dWJCDao;
    private final BHXHRJBBDao bHXHRJBBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dWLXDaoConfig = daoConfigMap.get(DWLXDao.class).clone();
        dWLXDaoConfig.initIdentityScope(type);

        jZXHDaoConfig = daoConfigMap.get(JZXHDao.class).clone();
        jZXHDaoConfig.initIdentityScope(type);

        aKXTDaoConfig = daoConfigMap.get(AKXTDao.class).clone();
        aKXTDaoConfig.initIdentityScope(type);

        zZCJDaoConfig = daoConfigMap.get(ZZCJDao.class).clone();
        zZCJDaoConfig.initIdentityScope(type);

        bZSJFLDaoConfig = daoConfigMap.get(BZSJFLDao.class).clone();
        bZSJFLDaoConfig.initIdentityScope(type);

        cCXXDaoConfig = daoConfigMap.get(CCXXDao.class).clone();
        cCXXDaoConfig.initIdentityScope(type);

        aKXTGXDaoConfig = daoConfigMap.get(AKXTGXDao.class).clone();
        aKXTGXDaoConfig.initIdentityScope(type);

        sBXXDaoConfig = daoConfigMap.get(SBXXDao.class).clone();
        sBXXDaoConfig.initIdentityScope(type);

        fZBHSBDaoConfig = daoConfigMap.get(FZBHSBDao.class).clone();
        fZBHSBDaoConfig.initIdentityScope(type);

        cCXXBKDaoConfig = daoConfigMap.get(CCXXBKDao.class).clone();
        cCXXBKDaoConfig.initIdentityScope(type);

        rZGLDaoConfig = daoConfigMap.get(RZGLDao.class).clone();
        rZGLDaoConfig.initIdentityScope(type);

        cCXXRJBBDaoConfig = daoConfigMap.get(CCXXRJBBDao.class).clone();
        cCXXRJBBDaoConfig.initIdentityScope(type);

        bKXXDaoConfig = daoConfigMap.get(BKXXDao.class).clone();
        bKXXDaoConfig.initIdentityScope(type);

        sBZCXXDaoConfig = daoConfigMap.get(SBZCXXDao.class).clone();
        sBZCXXDaoConfig.initIdentityScope(type);

        bZSJDaoConfig = daoConfigMap.get(BZSJDao.class).clone();
        bZSJDaoConfig.initIdentityScope(type);

        lJQXXDaoConfig = daoConfigMap.get(LJQXXDao.class).clone();
        lJQXXDaoConfig.initIdentityScope(type);

        jGCSDaoConfig = daoConfigMap.get(JGCSDao.class).clone();
        jGCSDaoConfig.initIdentityScope(type);

        mXCSDaoConfig = daoConfigMap.get(MXCSDao.class).clone();
        mXCSDaoConfig.initIdentityScope(type);

        dKQCSDaoConfig = daoConfigMap.get(DKQCSDao.class).clone();
        dKQCSDaoConfig.initIdentityScope(type);

        xLCSDaoConfig = daoConfigMap.get(XLCSDao.class).clone();
        xLCSDaoConfig.initIdentityScope(type);

        dDJCSDaoConfig = daoConfigMap.get(DDJCSDao.class).clone();
        dDJCSDaoConfig.initIdentityScope(type);

        dRQCSDaoConfig = daoConfigMap.get(DRQCSDao.class).clone();
        dRQCSDaoConfig.initIdentityScope(type);

        bYQCSDaoConfig = daoConfigMap.get(BYQCSDao.class).clone();
        bYQCSDaoConfig.initIdentityScope(type);

        fDJCSDaoConfig = daoConfigMap.get(FDJCSDao.class).clone();
        fDJCSDaoConfig.initIdentityScope(type);

        cZCSDaoConfig = daoConfigMap.get(CZCSDao.class).clone();
        cZCSDaoConfig.initIdentityScope(type);

        dLQCSDaoConfig = daoConfigMap.get(DLQCSDao.class).clone();
        dLQCSDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        tDXXDaoConfig = daoConfigMap.get(TDXXDao.class).clone();
        tDXXDaoConfig.initIdentityScope(type);

        pZTDGXDaoConfig = daoConfigMap.get(PZTDGXDao.class).clone();
        pZTDGXDaoConfig.initIdentityScope(type);

        bHLBXHDaoConfig = daoConfigMap.get(BHLBXHDao.class).clone();
        bHLBXHDaoConfig.initIdentityScope(type);

        lTYSBXHDaoConfig = daoConfigMap.get(LTYSBXHDao.class).clone();
        lTYSBXHDaoConfig.initIdentityScope(type);

        bDWDaoConfig = daoConfigMap.get(BDWDao.class).clone();
        bDWDaoConfig.initIdentityScope(type);

        cODEDaoConfig = daoConfigMap.get(CODEDao.class).clone();
        cODEDaoConfig.initIdentityScope(type);

        bHSBXHBDaoConfig = daoConfigMap.get(BHSBXHBDao.class).clone();
        bHSBXHBDaoConfig.initIdentityScope(type);

        bHPZDaoConfig = daoConfigMap.get(BHPZDao.class).clone();
        bHPZDaoConfig.initIdentityScope(type);

        wDGLDaoConfig = daoConfigMap.get(WDGLDao.class).clone();
        wDGLDaoConfig.initIdentityScope(type);

        bHPZXHBBGXDaoConfig = daoConfigMap.get(BHPZXHBBGXDao.class).clone();
        bHPZXHBBGXDaoConfig.initIdentityScope(type);

        dLQKDaoConfig = daoConfigMap.get(DLQKDao.class).clone();
        dLQKDaoConfig.initIdentityScope(type);

        gXDWDaoConfig = daoConfigMap.get(GXDWDao.class).clone();
        gXDWDaoConfig.initIdentityScope(type);

        fZBHSBXHBBGXDaoConfig = daoConfigMap.get(FZBHSBXHBBGXDao.class).clone();
        fZBHSBXHBBGXDaoConfig.initIdentityScope(type);

        rLST_USERDaoConfig = daoConfigMap.get(RLST_USERDao.class).clone();
        rLST_USERDaoConfig.initIdentityScope(type);

        iCDXXDaoConfig = daoConfigMap.get(ICDXXDao.class).clone();
        iCDXXDaoConfig.initIdentityScope(type);

        dWJCDaoConfig = daoConfigMap.get(DWJCDao.class).clone();
        dWJCDaoConfig.initIdentityScope(type);

        bHXHRJBBDaoConfig = daoConfigMap.get(BHXHRJBBDao.class).clone();
        bHXHRJBBDaoConfig.initIdentityScope(type);

        dWLXDao = new DWLXDao(dWLXDaoConfig, this);
        jZXHDao = new JZXHDao(jZXHDaoConfig, this);
        aKXTDao = new AKXTDao(aKXTDaoConfig, this);
        zZCJDao = new ZZCJDao(zZCJDaoConfig, this);
        bZSJFLDao = new BZSJFLDao(bZSJFLDaoConfig, this);
        cCXXDao = new CCXXDao(cCXXDaoConfig, this);
        aKXTGXDao = new AKXTGXDao(aKXTGXDaoConfig, this);
        sBXXDao = new SBXXDao(sBXXDaoConfig, this);
        fZBHSBDao = new FZBHSBDao(fZBHSBDaoConfig, this);
        cCXXBKDao = new CCXXBKDao(cCXXBKDaoConfig, this);
        rZGLDao = new RZGLDao(rZGLDaoConfig, this);
        cCXXRJBBDao = new CCXXRJBBDao(cCXXRJBBDaoConfig, this);
        bKXXDao = new BKXXDao(bKXXDaoConfig, this);
        sBZCXXDao = new SBZCXXDao(sBZCXXDaoConfig, this);
        bZSJDao = new BZSJDao(bZSJDaoConfig, this);
        lJQXXDao = new LJQXXDao(lJQXXDaoConfig, this);
        jGCSDao = new JGCSDao(jGCSDaoConfig, this);
        mXCSDao = new MXCSDao(mXCSDaoConfig, this);
        dKQCSDao = new DKQCSDao(dKQCSDaoConfig, this);
        xLCSDao = new XLCSDao(xLCSDaoConfig, this);
        dDJCSDao = new DDJCSDao(dDJCSDaoConfig, this);
        dRQCSDao = new DRQCSDao(dRQCSDaoConfig, this);
        bYQCSDao = new BYQCSDao(bYQCSDaoConfig, this);
        fDJCSDao = new FDJCSDao(fDJCSDaoConfig, this);
        cZCSDao = new CZCSDao(cZCSDaoConfig, this);
        dLQCSDao = new DLQCSDao(dLQCSDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        tDXXDao = new TDXXDao(tDXXDaoConfig, this);
        pZTDGXDao = new PZTDGXDao(pZTDGXDaoConfig, this);
        bHLBXHDao = new BHLBXHDao(bHLBXHDaoConfig, this);
        lTYSBXHDao = new LTYSBXHDao(lTYSBXHDaoConfig, this);
        bDWDao = new BDWDao(bDWDaoConfig, this);
        cODEDao = new CODEDao(cODEDaoConfig, this);
        bHSBXHBDao = new BHSBXHBDao(bHSBXHBDaoConfig, this);
        bHPZDao = new BHPZDao(bHPZDaoConfig, this);
        wDGLDao = new WDGLDao(wDGLDaoConfig, this);
        bHPZXHBBGXDao = new BHPZXHBBGXDao(bHPZXHBBGXDaoConfig, this);
        dLQKDao = new DLQKDao(dLQKDaoConfig, this);
        gXDWDao = new GXDWDao(gXDWDaoConfig, this);
        fZBHSBXHBBGXDao = new FZBHSBXHBBGXDao(fZBHSBXHBBGXDaoConfig, this);
        rLST_USERDao = new RLST_USERDao(rLST_USERDaoConfig, this);
        iCDXXDao = new ICDXXDao(iCDXXDaoConfig, this);
        dWJCDao = new DWJCDao(dWJCDaoConfig, this);
        bHXHRJBBDao = new BHXHRJBBDao(bHXHRJBBDaoConfig, this);

        registerDao(DWLX.class, dWLXDao);
        registerDao(JZXH.class, jZXHDao);
        registerDao(AKXT.class, aKXTDao);
        registerDao(ZZCJ.class, zZCJDao);
        registerDao(BZSJFL.class, bZSJFLDao);
        registerDao(CCXX.class, cCXXDao);
        registerDao(AKXTGX.class, aKXTGXDao);
        registerDao(SBXX.class, sBXXDao);
        registerDao(FZBHSB.class, fZBHSBDao);
        registerDao(CCXXBK.class, cCXXBKDao);
        registerDao(RZGL.class, rZGLDao);
        registerDao(CCXXRJBB.class, cCXXRJBBDao);
        registerDao(BKXX.class, bKXXDao);
        registerDao(SBZCXX.class, sBZCXXDao);
        registerDao(BZSJ.class, bZSJDao);
        registerDao(LJQXX.class, lJQXXDao);
        registerDao(JGCS.class, jGCSDao);
        registerDao(MXCS.class, mXCSDao);
        registerDao(DKQCS.class, dKQCSDao);
        registerDao(XLCS.class, xLCSDao);
        registerDao(DDJCS.class, dDJCSDao);
        registerDao(DRQCS.class, dRQCSDao);
        registerDao(BYQCS.class, bYQCSDao);
        registerDao(FDJCS.class, fDJCSDao);
        registerDao(CZCS.class, cZCSDao);
        registerDao(DLQCS.class, dLQCSDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(TDXX.class, tDXXDao);
        registerDao(PZTDGX.class, pZTDGXDao);
        registerDao(BHLBXH.class, bHLBXHDao);
        registerDao(LTYSBXH.class, lTYSBXHDao);
        registerDao(BDW.class, bDWDao);
        registerDao(CODE.class, cODEDao);
        registerDao(BHSBXHB.class, bHSBXHBDao);
        registerDao(BHPZ.class, bHPZDao);
        registerDao(WDGL.class, wDGLDao);
        registerDao(BHPZXHBBGX.class, bHPZXHBBGXDao);
        registerDao(DLQK.class, dLQKDao);
        registerDao(GXDW.class, gXDWDao);
        registerDao(FZBHSBXHBBGX.class, fZBHSBXHBBGXDao);
        registerDao(RLST_USER.class, rLST_USERDao);
        registerDao(ICDXX.class, iCDXXDao);
        registerDao(DWJC.class, dWJCDao);
        registerDao(BHXHRJBB.class, bHXHRJBBDao);
    }
    
    public void clear() {
        dWLXDaoConfig.clearIdentityScope();
        jZXHDaoConfig.clearIdentityScope();
        aKXTDaoConfig.clearIdentityScope();
        zZCJDaoConfig.clearIdentityScope();
        bZSJFLDaoConfig.clearIdentityScope();
        cCXXDaoConfig.clearIdentityScope();
        aKXTGXDaoConfig.clearIdentityScope();
        sBXXDaoConfig.clearIdentityScope();
        fZBHSBDaoConfig.clearIdentityScope();
        cCXXBKDaoConfig.clearIdentityScope();
        rZGLDaoConfig.clearIdentityScope();
        cCXXRJBBDaoConfig.clearIdentityScope();
        bKXXDaoConfig.clearIdentityScope();
        sBZCXXDaoConfig.clearIdentityScope();
        bZSJDaoConfig.clearIdentityScope();
        lJQXXDaoConfig.clearIdentityScope();
        jGCSDaoConfig.clearIdentityScope();
        mXCSDaoConfig.clearIdentityScope();
        dKQCSDaoConfig.clearIdentityScope();
        xLCSDaoConfig.clearIdentityScope();
        dDJCSDaoConfig.clearIdentityScope();
        dRQCSDaoConfig.clearIdentityScope();
        bYQCSDaoConfig.clearIdentityScope();
        fDJCSDaoConfig.clearIdentityScope();
        cZCSDaoConfig.clearIdentityScope();
        dLQCSDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        tDXXDaoConfig.clearIdentityScope();
        pZTDGXDaoConfig.clearIdentityScope();
        bHLBXHDaoConfig.clearIdentityScope();
        lTYSBXHDaoConfig.clearIdentityScope();
        bDWDaoConfig.clearIdentityScope();
        cODEDaoConfig.clearIdentityScope();
        bHSBXHBDaoConfig.clearIdentityScope();
        bHPZDaoConfig.clearIdentityScope();
        wDGLDaoConfig.clearIdentityScope();
        bHPZXHBBGXDaoConfig.clearIdentityScope();
        dLQKDaoConfig.clearIdentityScope();
        gXDWDaoConfig.clearIdentityScope();
        fZBHSBXHBBGXDaoConfig.clearIdentityScope();
        rLST_USERDaoConfig.clearIdentityScope();
        iCDXXDaoConfig.clearIdentityScope();
        dWJCDaoConfig.clearIdentityScope();
        bHXHRJBBDaoConfig.clearIdentityScope();
    }

    public DWLXDao getDWLXDao() {
        return dWLXDao;
    }

    public JZXHDao getJZXHDao() {
        return jZXHDao;
    }

    public AKXTDao getAKXTDao() {
        return aKXTDao;
    }

    public ZZCJDao getZZCJDao() {
        return zZCJDao;
    }

    public BZSJFLDao getBZSJFLDao() {
        return bZSJFLDao;
    }

    public CCXXDao getCCXXDao() {
        return cCXXDao;
    }

    public AKXTGXDao getAKXTGXDao() {
        return aKXTGXDao;
    }

    public SBXXDao getSBXXDao() {
        return sBXXDao;
    }

    public FZBHSBDao getFZBHSBDao() {
        return fZBHSBDao;
    }

    public CCXXBKDao getCCXXBKDao() {
        return cCXXBKDao;
    }

    public RZGLDao getRZGLDao() {
        return rZGLDao;
    }

    public CCXXRJBBDao getCCXXRJBBDao() {
        return cCXXRJBBDao;
    }

    public BKXXDao getBKXXDao() {
        return bKXXDao;
    }

    public SBZCXXDao getSBZCXXDao() {
        return sBZCXXDao;
    }

    public BZSJDao getBZSJDao() {
        return bZSJDao;
    }

    public LJQXXDao getLJQXXDao() {
        return lJQXXDao;
    }

    public JGCSDao getJGCSDao() {
        return jGCSDao;
    }

    public MXCSDao getMXCSDao() {
        return mXCSDao;
    }

    public DKQCSDao getDKQCSDao() {
        return dKQCSDao;
    }

    public XLCSDao getXLCSDao() {
        return xLCSDao;
    }

    public DDJCSDao getDDJCSDao() {
        return dDJCSDao;
    }

    public DRQCSDao getDRQCSDao() {
        return dRQCSDao;
    }

    public BYQCSDao getBYQCSDao() {
        return bYQCSDao;
    }

    public FDJCSDao getFDJCSDao() {
        return fDJCSDao;
    }

    public CZCSDao getCZCSDao() {
        return cZCSDao;
    }

    public DLQCSDao getDLQCSDao() {
        return dLQCSDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public TDXXDao getTDXXDao() {
        return tDXXDao;
    }

    public PZTDGXDao getPZTDGXDao() {
        return pZTDGXDao;
    }

    public BHLBXHDao getBHLBXHDao() {
        return bHLBXHDao;
    }

    public LTYSBXHDao getLTYSBXHDao() {
        return lTYSBXHDao;
    }

    public BDWDao getBDWDao() {
        return bDWDao;
    }

    public CODEDao getCODEDao() {
        return cODEDao;
    }

    public BHSBXHBDao getBHSBXHBDao() {
        return bHSBXHBDao;
    }

    public BHPZDao getBHPZDao() {
        return bHPZDao;
    }

    public WDGLDao getWDGLDao() {
        return wDGLDao;
    }

    public BHPZXHBBGXDao getBHPZXHBBGXDao() {
        return bHPZXHBBGXDao;
    }

    public DLQKDao getDLQKDao() {
        return dLQKDao;
    }

    public GXDWDao getGXDWDao() {
        return gXDWDao;
    }

    public FZBHSBXHBBGXDao getFZBHSBXHBBGXDao() {
        return fZBHSBXHBBGXDao;
    }

    public RLST_USERDao getRLST_USERDao() {
        return rLST_USERDao;
    }

    public ICDXXDao getICDXXDao() {
        return iCDXXDao;
    }

    public DWJCDao getDWJCDao() {
        return dWJCDao;
    }

    public BHXHRJBBDao getBHXHRJBBDao() {
        return bHXHRJBBDao;
    }

}
