package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.ycsb.DKQCS;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DKQCS".
*/
public class DKQCSDao extends AbstractDao<DKQCS, Long> {

    public static final String TABLENAME = "DKQCS";

    /**
     * Properties of entity DKQCS.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Vf = new Property(0, int.class, "vf", false, "VF");
        public final static Property Id = new Property(1, Long.class, "id", true, "ID");
        public final static Property Bh = new Property(2, String.class, "bh", false, "BH");
        public final static Property Dkqlx = new Property(3, String.class, "dkqlx", false, "TYPE");
        public final static Property Dkqmc = new Property(4, String.class, "dkqmc", false, "DKQMC");
        public final static Property Czmc = new Property(5, String.class, "czmc", false, "CZMC");
        public final static Property Bz = new Property(6, String.class, "bz", false, "BZ");
        public final static Property Sh = new Property(7, String.class, "sh", false, "SH");
        public final static Property Shr2 = new Property(8, String.class, "shr2", false, "SHR");
        public final static Property Shyy = new Property(9, String.class, "shyy", false, "SHYY");
        public final static Property Dydj = new Property(10, int.class, "dydj", false, "DYDJ");
        public final static Property KGBH = new Property(11, String.class, "KGBH", false, "KGBH");
        public final static Property Sftcyx = new Property(12, String.class, "sftcyx", false, "SFTCYX");
        public final static Property Gldw = new Property(13, String.class, "gldw", false, "GLDW");
        public final static Property WDID = new Property(14, int.class, "WDID", false, "WDID");
        public final static Property Czr = new Property(15, String.class, "czr", false, "CZR");
        public final static Property Tjr = new Property(16, String.class, "tjr", false, "TJR");
        public final static Property Dwtjr = new Property(17, String.class, "dwtjr", false, "DWTJR");
        public final static Property Dddw = new Property(18, String.class, "dddw", false, "DDDW");
        public final static Property Jglx = new Property(19, String.class, "jglx", false, "JGLX");
        public final static Property Jgmc = new Property(20, String.class, "jgmc", false, "JGMC");
        public final static Property CZSJ = new Property(21, java.util.Date.class, "CZSJ", false, "CZSJ");
        public final static Property SFBDSJ = new Property(22, String.class, "SFBDSJ", false, "SFBDSJ");
        public final static Property SB = new Property(23, String.class, "SB", false, "SB");
        public final static Property SBSJ = new Property(24, java.util.Date.class, "SBSJ", false, "SBSJ");
        public final static Property SB_LS_ID = new Property(25, String.class, "SB_LS_ID", false, "SB_LS_ID");
        public final static Property SBDW = new Property(26, String.class, "SBDW", false, "SBDW");
        public final static Property HZSJ = new Property(27, java.util.Date.class, "HZSJ", false, "HZSJ");
        public final static Property SBCZLX = new Property(28, String.class, "SBCZLX", false, "SBCZLX");
        public final static Property SFXTLR = new Property(29, String.class, "SFXTLR", false, "SFXTLR");
        public final static Property WJ_DW = new Property(30, String.class, "WJ_DW", false, "WJ_DW");
        public final static Property WJ_LS_ID = new Property(31, String.class, "WJ_LS_ID", false, "WJ_LS_ID");
    }


    public DKQCSDao(DaoConfig config) {
        super(config);
    }
    
    public DKQCSDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DKQCS entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getVf());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String bh = entity.getBh();
        if (bh != null) {
            stmt.bindString(3, bh);
        }
 
        String dkqlx = entity.getDkqlx();
        if (dkqlx != null) {
            stmt.bindString(4, dkqlx);
        }
 
        String dkqmc = entity.getDkqmc();
        if (dkqmc != null) {
            stmt.bindString(5, dkqmc);
        }
 
        String czmc = entity.getCzmc();
        if (czmc != null) {
            stmt.bindString(6, czmc);
        }
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(7, bz);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(8, sh);
        }
 
        String shr2 = entity.getShr2();
        if (shr2 != null) {
            stmt.bindString(9, shr2);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(10, shyy);
        }
        stmt.bindLong(11, entity.getDydj());
 
        String KGBH = entity.getKGBH();
        if (KGBH != null) {
            stmt.bindString(12, KGBH);
        }
 
        String sftcyx = entity.getSftcyx();
        if (sftcyx != null) {
            stmt.bindString(13, sftcyx);
        }
 
        String gldw = entity.getGldw();
        if (gldw != null) {
            stmt.bindString(14, gldw);
        }
        stmt.bindLong(15, entity.getWDID());
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(16, czr);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(17, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(18, dwtjr);
        }
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(19, dddw);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(20, jglx);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(21, jgmc);
        }
 
        java.util.Date CZSJ = entity.getCZSJ();
        if (CZSJ != null) {
            stmt.bindLong(22, CZSJ.getTime());
        }
 
        String SFBDSJ = entity.getSFBDSJ();
        if (SFBDSJ != null) {
            stmt.bindString(23, SFBDSJ);
        }
 
        String SB = entity.getSB();
        if (SB != null) {
            stmt.bindString(24, SB);
        }
 
        java.util.Date SBSJ = entity.getSBSJ();
        if (SBSJ != null) {
            stmt.bindLong(25, SBSJ.getTime());
        }
 
        String SB_LS_ID = entity.getSB_LS_ID();
        if (SB_LS_ID != null) {
            stmt.bindString(26, SB_LS_ID);
        }
 
        String SBDW = entity.getSBDW();
        if (SBDW != null) {
            stmt.bindString(27, SBDW);
        }
 
        java.util.Date HZSJ = entity.getHZSJ();
        if (HZSJ != null) {
            stmt.bindLong(28, HZSJ.getTime());
        }
 
        String SBCZLX = entity.getSBCZLX();
        if (SBCZLX != null) {
            stmt.bindString(29, SBCZLX);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(30, SFXTLR);
        }
 
        String WJ_DW = entity.getWJ_DW();
        if (WJ_DW != null) {
            stmt.bindString(31, WJ_DW);
        }
 
        String WJ_LS_ID = entity.getWJ_LS_ID();
        if (WJ_LS_ID != null) {
            stmt.bindString(32, WJ_LS_ID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DKQCS entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getVf());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String bh = entity.getBh();
        if (bh != null) {
            stmt.bindString(3, bh);
        }
 
        String dkqlx = entity.getDkqlx();
        if (dkqlx != null) {
            stmt.bindString(4, dkqlx);
        }
 
        String dkqmc = entity.getDkqmc();
        if (dkqmc != null) {
            stmt.bindString(5, dkqmc);
        }
 
        String czmc = entity.getCzmc();
        if (czmc != null) {
            stmt.bindString(6, czmc);
        }
 
        String bz = entity.getBz();
        if (bz != null) {
            stmt.bindString(7, bz);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(8, sh);
        }
 
        String shr2 = entity.getShr2();
        if (shr2 != null) {
            stmt.bindString(9, shr2);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(10, shyy);
        }
        stmt.bindLong(11, entity.getDydj());
 
        String KGBH = entity.getKGBH();
        if (KGBH != null) {
            stmt.bindString(12, KGBH);
        }
 
        String sftcyx = entity.getSftcyx();
        if (sftcyx != null) {
            stmt.bindString(13, sftcyx);
        }
 
        String gldw = entity.getGldw();
        if (gldw != null) {
            stmt.bindString(14, gldw);
        }
        stmt.bindLong(15, entity.getWDID());
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(16, czr);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(17, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(18, dwtjr);
        }
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(19, dddw);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(20, jglx);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(21, jgmc);
        }
 
        java.util.Date CZSJ = entity.getCZSJ();
        if (CZSJ != null) {
            stmt.bindLong(22, CZSJ.getTime());
        }
 
        String SFBDSJ = entity.getSFBDSJ();
        if (SFBDSJ != null) {
            stmt.bindString(23, SFBDSJ);
        }
 
        String SB = entity.getSB();
        if (SB != null) {
            stmt.bindString(24, SB);
        }
 
        java.util.Date SBSJ = entity.getSBSJ();
        if (SBSJ != null) {
            stmt.bindLong(25, SBSJ.getTime());
        }
 
        String SB_LS_ID = entity.getSB_LS_ID();
        if (SB_LS_ID != null) {
            stmt.bindString(26, SB_LS_ID);
        }
 
        String SBDW = entity.getSBDW();
        if (SBDW != null) {
            stmt.bindString(27, SBDW);
        }
 
        java.util.Date HZSJ = entity.getHZSJ();
        if (HZSJ != null) {
            stmt.bindLong(28, HZSJ.getTime());
        }
 
        String SBCZLX = entity.getSBCZLX();
        if (SBCZLX != null) {
            stmt.bindString(29, SBCZLX);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(30, SFXTLR);
        }
 
        String WJ_DW = entity.getWJ_DW();
        if (WJ_DW != null) {
            stmt.bindString(31, WJ_DW);
        }
 
        String WJ_LS_ID = entity.getWJ_LS_ID();
        if (WJ_LS_ID != null) {
            stmt.bindString(32, WJ_LS_ID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public DKQCS readEntity(Cursor cursor, int offset) {
        DKQCS entity = new DKQCS( //
            cursor.getInt(offset + 0), // vf
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bh
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dkqlx
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dkqmc
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // czmc
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bz
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // sh
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // shr2
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // shyy
            cursor.getInt(offset + 10), // dydj
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // KGBH
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // sftcyx
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // gldw
            cursor.getInt(offset + 14), // WDID
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // czr
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tjr
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // dwtjr
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // dddw
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // jglx
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // jgmc
            cursor.isNull(offset + 21) ? null : new java.util.Date(cursor.getLong(offset + 21)), // CZSJ
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // SFBDSJ
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // SB
            cursor.isNull(offset + 24) ? null : new java.util.Date(cursor.getLong(offset + 24)), // SBSJ
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // SB_LS_ID
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // SBDW
            cursor.isNull(offset + 27) ? null : new java.util.Date(cursor.getLong(offset + 27)), // HZSJ
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // SBCZLX
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // SFXTLR
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // WJ_DW
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31) // WJ_LS_ID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DKQCS entity, int offset) {
        entity.setVf(cursor.getInt(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setBh(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDkqlx(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDkqmc(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCzmc(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBz(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSh(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setShr2(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setShyy(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDydj(cursor.getInt(offset + 10));
        entity.setKGBH(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setSftcyx(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setGldw(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setWDID(cursor.getInt(offset + 14));
        entity.setCzr(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTjr(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setDwtjr(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setDddw(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setJglx(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setJgmc(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setCZSJ(cursor.isNull(offset + 21) ? null : new java.util.Date(cursor.getLong(offset + 21)));
        entity.setSFBDSJ(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setSB(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setSBSJ(cursor.isNull(offset + 24) ? null : new java.util.Date(cursor.getLong(offset + 24)));
        entity.setSB_LS_ID(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setSBDW(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setHZSJ(cursor.isNull(offset + 27) ? null : new java.util.Date(cursor.getLong(offset + 27)));
        entity.setSBCZLX(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setSFXTLR(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setWJ_DW(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setWJ_LS_ID(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DKQCS entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DKQCS entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DKQCS entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
