package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.ycsb.DRQCS;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DRQCS".
*/
public class DRQCSDao extends AbstractDao<DRQCS, Long> {

    public static final String TABLENAME = "DRQCS";

    /**
     * Properties of entity DRQCS.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Vf = new Property(0, int.class, "vf", false, "VF");
        public final static Property Id = new Property(1, Long.class, "id", true, "ID");
        public final static Property BH = new Property(2, String.class, "BH", false, "BH");
        public final static Property DRQMC = new Property(3, String.class, "DRQMC", false, "DRQMC");
        public final static Property CZMC = new Property(4, String.class, "CZMC", false, "CZMC");
        public final static Property DYDJ = new Property(5, int.class, "DYDJ", false, "DYDJ");
        public final static Property KGBH = new Property(6, String.class, "KGBH", false, "KGBH");
        public final static Property SFTCYX = new Property(7, String.class, "SFTCYX", false, "SFTCYX");
        public final static Property BZ = new Property(8, String.class, "BZ", false, "BZ");
        public final static Property Sh = new Property(9, String.class, "sh", false, "SH");
        public final static Property Shr2 = new Property(10, String.class, "shr2", false, "SHR");
        public final static Property Shyy = new Property(11, String.class, "shyy", false, "SHYY");
        public final static Property GLDW = new Property(12, String.class, "GLDW", false, "GLDW");
        public final static Property WDID = new Property(13, int.class, "WDID", false, "WDID");
        public final static Property Dddw = new Property(14, String.class, "dddw", false, "DDDW");
        public final static Property Czr = new Property(15, String.class, "czr", false, "CZR");
        public final static Property Tjr = new Property(16, String.class, "tjr", false, "TJR");
        public final static Property Dwtjr = new Property(17, String.class, "dwtjr", false, "DWTJR");
        public final static Property Jglx = new Property(18, String.class, "jglx", false, "JGLX");
        public final static Property Jgmc = new Property(19, String.class, "jgmc", false, "JGMC");
        public final static Property CZSJ = new Property(20, java.util.Date.class, "CZSJ", false, "CZSJ");
        public final static Property SFBDSJ = new Property(21, String.class, "SFBDSJ", false, "SFBDSJ");
        public final static Property SB = new Property(22, String.class, "SB", false, "SB");
        public final static Property SBSJ = new Property(23, java.util.Date.class, "SBSJ", false, "SBSJ");
        public final static Property SB_LS_ID = new Property(24, String.class, "SB_LS_ID", false, "SB_LS_ID");
        public final static Property SBDW = new Property(25, String.class, "SBDW", false, "SBDW");
        public final static Property HZSJ = new Property(26, java.util.Date.class, "HZSJ", false, "HZSJ");
        public final static Property SBCZLX = new Property(27, String.class, "SBCZLX", false, "SBCZLX");
        public final static Property SFXTLR = new Property(28, String.class, "SFXTLR", false, "SFXTLR");
        public final static Property WJ_DW = new Property(29, String.class, "WJ_DW", false, "WJ_DW");
        public final static Property WJ_LS_ID = new Property(30, String.class, "WJ_LS_ID", false, "WJ_LS_ID");
    }


    public DRQCSDao(DaoConfig config) {
        super(config);
    }
    
    public DRQCSDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DRQCS entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getVf());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String BH = entity.getBH();
        if (BH != null) {
            stmt.bindString(3, BH);
        }
 
        String DRQMC = entity.getDRQMC();
        if (DRQMC != null) {
            stmt.bindString(4, DRQMC);
        }
 
        String CZMC = entity.getCZMC();
        if (CZMC != null) {
            stmt.bindString(5, CZMC);
        }
        stmt.bindLong(6, entity.getDYDJ());
 
        String KGBH = entity.getKGBH();
        if (KGBH != null) {
            stmt.bindString(7, KGBH);
        }
 
        String SFTCYX = entity.getSFTCYX();
        if (SFTCYX != null) {
            stmt.bindString(8, SFTCYX);
        }
 
        String BZ = entity.getBZ();
        if (BZ != null) {
            stmt.bindString(9, BZ);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(10, sh);
        }
 
        String shr2 = entity.getShr2();
        if (shr2 != null) {
            stmt.bindString(11, shr2);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(12, shyy);
        }
 
        String GLDW = entity.getGLDW();
        if (GLDW != null) {
            stmt.bindString(13, GLDW);
        }
        stmt.bindLong(14, entity.getWDID());
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(15, dddw);
        }
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(16, czr);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(17, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(18, dwtjr);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(19, jglx);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(20, jgmc);
        }
 
        java.util.Date CZSJ = entity.getCZSJ();
        if (CZSJ != null) {
            stmt.bindLong(21, CZSJ.getTime());
        }
 
        String SFBDSJ = entity.getSFBDSJ();
        if (SFBDSJ != null) {
            stmt.bindString(22, SFBDSJ);
        }
 
        String SB = entity.getSB();
        if (SB != null) {
            stmt.bindString(23, SB);
        }
 
        java.util.Date SBSJ = entity.getSBSJ();
        if (SBSJ != null) {
            stmt.bindLong(24, SBSJ.getTime());
        }
 
        String SB_LS_ID = entity.getSB_LS_ID();
        if (SB_LS_ID != null) {
            stmt.bindString(25, SB_LS_ID);
        }
 
        String SBDW = entity.getSBDW();
        if (SBDW != null) {
            stmt.bindString(26, SBDW);
        }
 
        java.util.Date HZSJ = entity.getHZSJ();
        if (HZSJ != null) {
            stmt.bindLong(27, HZSJ.getTime());
        }
 
        String SBCZLX = entity.getSBCZLX();
        if (SBCZLX != null) {
            stmt.bindString(28, SBCZLX);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(29, SFXTLR);
        }
 
        String WJ_DW = entity.getWJ_DW();
        if (WJ_DW != null) {
            stmt.bindString(30, WJ_DW);
        }
 
        String WJ_LS_ID = entity.getWJ_LS_ID();
        if (WJ_LS_ID != null) {
            stmt.bindString(31, WJ_LS_ID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DRQCS entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getVf());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String BH = entity.getBH();
        if (BH != null) {
            stmt.bindString(3, BH);
        }
 
        String DRQMC = entity.getDRQMC();
        if (DRQMC != null) {
            stmt.bindString(4, DRQMC);
        }
 
        String CZMC = entity.getCZMC();
        if (CZMC != null) {
            stmt.bindString(5, CZMC);
        }
        stmt.bindLong(6, entity.getDYDJ());
 
        String KGBH = entity.getKGBH();
        if (KGBH != null) {
            stmt.bindString(7, KGBH);
        }
 
        String SFTCYX = entity.getSFTCYX();
        if (SFTCYX != null) {
            stmt.bindString(8, SFTCYX);
        }
 
        String BZ = entity.getBZ();
        if (BZ != null) {
            stmt.bindString(9, BZ);
        }
 
        String sh = entity.getSh();
        if (sh != null) {
            stmt.bindString(10, sh);
        }
 
        String shr2 = entity.getShr2();
        if (shr2 != null) {
            stmt.bindString(11, shr2);
        }
 
        String shyy = entity.getShyy();
        if (shyy != null) {
            stmt.bindString(12, shyy);
        }
 
        String GLDW = entity.getGLDW();
        if (GLDW != null) {
            stmt.bindString(13, GLDW);
        }
        stmt.bindLong(14, entity.getWDID());
 
        String dddw = entity.getDddw();
        if (dddw != null) {
            stmt.bindString(15, dddw);
        }
 
        String czr = entity.getCzr();
        if (czr != null) {
            stmt.bindString(16, czr);
        }
 
        String tjr = entity.getTjr();
        if (tjr != null) {
            stmt.bindString(17, tjr);
        }
 
        String dwtjr = entity.getDwtjr();
        if (dwtjr != null) {
            stmt.bindString(18, dwtjr);
        }
 
        String jglx = entity.getJglx();
        if (jglx != null) {
            stmt.bindString(19, jglx);
        }
 
        String jgmc = entity.getJgmc();
        if (jgmc != null) {
            stmt.bindString(20, jgmc);
        }
 
        java.util.Date CZSJ = entity.getCZSJ();
        if (CZSJ != null) {
            stmt.bindLong(21, CZSJ.getTime());
        }
 
        String SFBDSJ = entity.getSFBDSJ();
        if (SFBDSJ != null) {
            stmt.bindString(22, SFBDSJ);
        }
 
        String SB = entity.getSB();
        if (SB != null) {
            stmt.bindString(23, SB);
        }
 
        java.util.Date SBSJ = entity.getSBSJ();
        if (SBSJ != null) {
            stmt.bindLong(24, SBSJ.getTime());
        }
 
        String SB_LS_ID = entity.getSB_LS_ID();
        if (SB_LS_ID != null) {
            stmt.bindString(25, SB_LS_ID);
        }
 
        String SBDW = entity.getSBDW();
        if (SBDW != null) {
            stmt.bindString(26, SBDW);
        }
 
        java.util.Date HZSJ = entity.getHZSJ();
        if (HZSJ != null) {
            stmt.bindLong(27, HZSJ.getTime());
        }
 
        String SBCZLX = entity.getSBCZLX();
        if (SBCZLX != null) {
            stmt.bindString(28, SBCZLX);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(29, SFXTLR);
        }
 
        String WJ_DW = entity.getWJ_DW();
        if (WJ_DW != null) {
            stmt.bindString(30, WJ_DW);
        }
 
        String WJ_LS_ID = entity.getWJ_LS_ID();
        if (WJ_LS_ID != null) {
            stmt.bindString(31, WJ_LS_ID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public DRQCS readEntity(Cursor cursor, int offset) {
        DRQCS entity = new DRQCS( //
            cursor.getInt(offset + 0), // vf
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // BH
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // DRQMC
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // CZMC
            cursor.getInt(offset + 5), // DYDJ
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // KGBH
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // SFTCYX
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // BZ
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // sh
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // shr2
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // shyy
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // GLDW
            cursor.getInt(offset + 13), // WDID
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // dddw
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // czr
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tjr
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // dwtjr
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // jglx
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // jgmc
            cursor.isNull(offset + 20) ? null : new java.util.Date(cursor.getLong(offset + 20)), // CZSJ
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // SFBDSJ
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // SB
            cursor.isNull(offset + 23) ? null : new java.util.Date(cursor.getLong(offset + 23)), // SBSJ
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // SB_LS_ID
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // SBDW
            cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)), // HZSJ
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // SBCZLX
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // SFXTLR
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // WJ_DW
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30) // WJ_LS_ID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DRQCS entity, int offset) {
        entity.setVf(cursor.getInt(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setBH(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDRQMC(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCZMC(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDYDJ(cursor.getInt(offset + 5));
        entity.setKGBH(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSFTCYX(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBZ(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSh(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setShr2(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setShyy(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setGLDW(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setWDID(cursor.getInt(offset + 13));
        entity.setDddw(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCzr(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTjr(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setDwtjr(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setJglx(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setJgmc(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setCZSJ(cursor.isNull(offset + 20) ? null : new java.util.Date(cursor.getLong(offset + 20)));
        entity.setSFBDSJ(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setSB(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setSBSJ(cursor.isNull(offset + 23) ? null : new java.util.Date(cursor.getLong(offset + 23)));
        entity.setSB_LS_ID(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setSBDW(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setHZSJ(cursor.isNull(offset + 26) ? null : new java.util.Date(cursor.getLong(offset + 26)));
        entity.setSBCZLX(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setSFXTLR(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setWJ_DW(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setWJ_LS_ID(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DRQCS entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DRQCS entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DRQCS entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
