package cn.com.sgcc.dev.dao2;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.sgcc.dev.model2.FZBHSBXHBBGX;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FZBHSBXHBBGX".
*/
public class FZBHSBXHBBGXDao extends AbstractDao<FZBHSBXHBBGX, Long> {

    public static final String TABLENAME = "FZBHSBXHBBGX";

    /**
     * Properties of entity FZBHSBXHBBGX.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property FZBHSBID = new Property(1, long.class, "FZBHSBID", false, "FZBHSBID");
        public final static Property RJBBCODE = new Property(2, String.class, "RJBBCODE", false, "RJBBCODE");
        public final static Property SCSJ = new Property(3, String.class, "SCSJ", false, "SCSJ");
        public final static Property SFXTLR = new Property(4, String.class, "SFXTLR", false, "SFXTLR");
        public final static Property SB_FZBHSB_ID = new Property(5, String.class, "SB_FZBHSB_ID", false, "SB_FZBHSB_ID");
    }


    public FZBHSBXHBBGXDao(DaoConfig config) {
        super(config);
    }
    
    public FZBHSBXHBBGXDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FZBHSBXHBBGX entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getFZBHSBID());
 
        String RJBBCODE = entity.getRJBBCODE();
        if (RJBBCODE != null) {
            stmt.bindString(3, RJBBCODE);
        }
 
        String SCSJ = entity.getSCSJ();
        if (SCSJ != null) {
            stmt.bindString(4, SCSJ);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(5, SFXTLR);
        }
 
        String SB_FZBHSB_ID = entity.getSB_FZBHSB_ID();
        if (SB_FZBHSB_ID != null) {
            stmt.bindString(6, SB_FZBHSB_ID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FZBHSBXHBBGX entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getFZBHSBID());
 
        String RJBBCODE = entity.getRJBBCODE();
        if (RJBBCODE != null) {
            stmt.bindString(3, RJBBCODE);
        }
 
        String SCSJ = entity.getSCSJ();
        if (SCSJ != null) {
            stmt.bindString(4, SCSJ);
        }
 
        String SFXTLR = entity.getSFXTLR();
        if (SFXTLR != null) {
            stmt.bindString(5, SFXTLR);
        }
 
        String SB_FZBHSB_ID = entity.getSB_FZBHSB_ID();
        if (SB_FZBHSB_ID != null) {
            stmt.bindString(6, SB_FZBHSB_ID);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FZBHSBXHBBGX readEntity(Cursor cursor, int offset) {
        FZBHSBXHBBGX entity = new FZBHSBXHBBGX( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getLong(offset + 1), // FZBHSBID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // RJBBCODE
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // SCSJ
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // SFXTLR
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // SB_FZBHSB_ID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FZBHSBXHBBGX entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFZBHSBID(cursor.getLong(offset + 1));
        entity.setRJBBCODE(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSCSJ(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSFXTLR(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSB_FZBHSB_ID(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FZBHSBXHBBGX entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FZBHSBXHBBGX entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FZBHSBXHBBGX entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
